/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import java.util.List;
import qlsv.dao.HocKyD;
import qlsv.dao.impl.HocKyDAOImpl;
import qlsv.dao.impl.ThoiKhoaBieuDAOImpl;

/**
 *
 * @author ADMIN
 */
public class DiemJDialog extends javax.swing.JDialog {
    private boolean isSuaDiem = false;

    /**
     * Creates new form DiemJDialog
     */
    public DiemJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        fillCboHocKy();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboHocKy = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        cboMon = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiem = new javax.swing.JTable();
        btnNhapDiem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtMaSV = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        txtDiemFinal = new javax.swing.JTextField();
        txtDiemASM = new javax.swing.JTextField();
        txtDiemQuiz = new javax.swing.JTextField();
        txtDiemLab = new javax.swing.JTextField();
        cboHocKyChiTiet = new javax.swing.JComboBox<>();
        cboMaMon = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblSV = new javax.swing.JLabel();
        lblDat = new javax.swing.JLabel();
        lblTruot = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý điểm - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐIỂM ");

        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\CHINH.png")); // NOI18N
        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Chọn học kỳ : ");

        cboHocKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHocKyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Chọn môn : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Chọn Lớp : ");

        cboLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopActionPerformed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\tim.png")); // NOI18N
        btnTim.setText("Tìm ");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        tblDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên ", "Mã môn", "Tên môn ", "Học kỳ", "Điểm Lab", "Điểm Quiz", "Điểm ASM", "Điẻm Final", "Điẻm TB", "Ngày nhập", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDiem);

        btnNhapDiem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnNhapDiem.setText("Nhập điểm");
        btnNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDiemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSua.setText("Sửa điểm ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoa.setText("Xóa điểm ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thông tin chi tiết ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Mã SV : ");

        jLabel7.setText("Họ tên : ");

        jLabel8.setText("Tên môn : ");

        jLabel9.setText("Mã môn : ");

        jLabel10.setText("Học kỳ : ");

        jLabel12.setText("Điểm Final : ");

        jLabel13.setText("Điểm ASM : ");

        jLabel14.setText("Điểm Lab :");

        jLabel15.setText("Điểm Quiz : ");

        btnLuu.setBackground(new java.awt.Color(255, 255, 102));
        btnLuu.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Luu.png")); // NOI18N
        btnLuu.setText("Lưu ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Huy.png")); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboHocKyChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(cboMaMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiemASM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiemQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiemLab, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnLuu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHuy)))))
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(txtDiemLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(txtDiemQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13)
                        .addComponent(txtDiemASM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtDiemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cboHocKyChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnHuy))
                        .addGap(25, 25, 25))))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thống kê nhanh ");

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THONGKE.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel16.setText("Tổng số sinh viên : ");

        jLabel17.setText("Số sinh viên đạt : ");

        jLabel19.setText("Số sinh viên trượt : ");

        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LamMoi (1).png")); // NOI18N
        btnLamMoi.setText("Làm mới ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnTim))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNhapDiem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnLamMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSV, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTruot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboLop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboHocKy, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(btnTim)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapDiem)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblSV, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(lblTruot, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboHocKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHocKyActionPerformed
        // TODO add your handling code here:
        fillCboLop();
    }//GEN-LAST:event_cboHocKyActionPerformed

    private void cboLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopActionPerformed
        // TODO add your handling code here:
        fillCboMon(); 
    }//GEN-LAST:event_cboLopActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        tim();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDiemActionPerformed
        // TODO add your handling code here:
        isSuaDiem = false;
        hienThiThongTinChiTiet();
    }//GEN-LAST:event_btnNhapDiemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (isSuaDiem) {
        suaDiem();
    } else {
        luuDiem();
    }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
         isSuaDiem = true;
        hienThiThongTinChiTietSua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoaDiem();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int huy = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn hủy?",
        "Xác nhận hủy",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (huy == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose(); // Đóng form
    }
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiemJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiemJDialog dialog = new DiemJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapDiem;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHocKy;
    private javax.swing.JComboBox<String> cboHocKyChiTiet;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JComboBox<String> cboMaMon;
    private javax.swing.JComboBox<String> cboMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDat;
    private javax.swing.JLabel lblSV;
    private javax.swing.JLabel lblTruot;
    private javax.swing.JTable tblDiem;
    private javax.swing.JTextField txtDiemASM;
    private javax.swing.JTextField txtDiemFinal;
    private javax.swing.JTextField txtDiemLab;
    private javax.swing.JTextField txtDiemQuiz;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
    // cbo học kỳ 
    private void fillCboHocKy() {
    HocKyD hocKyDAO = new HocKyDAOImpl();
    List<String> dsHocKy = hocKyDAO.getAllMaHK();
    cboHocKy.removeAllItems();
    for (String maHK : dsHocKy) {
        cboHocKy.addItem(maHK);
    }
}
    // cbo cho lớp 
    private void fillCboLop() {
    String maHK = (String) cboHocKy.getSelectedItem();
    if (maHK == null) return;
    // DAO lấy danh sách lớp theo học kỳ
    List<String> dsLop = new ThoiKhoaBieuDAOImpl().getLopByHocKy(maHK);
    cboLop.removeAllItems();
    for (String maLop : dsLop) {
        cboLop.addItem(maLop);
    }
}
  // cbo của môn học 
  private void fillCboMon() {
    String maLop = (String) cboLop.getSelectedItem();
    String maHK = (String) cboHocKy.getSelectedItem();
    if (maLop == null || maHK == null) return;
    List<String> dsMon = new ThoiKhoaBieuDAOImpl().getMonByLopVaHocKy(maLop, maHK);
    cboMon.removeAllItems();
    for (String maMH : dsMon) {
        cboMon.addItem(maMH);
    }
}
// sự kiện của nút tìm 
private void tim() {
    String maHK = (String) cboHocKy.getSelectedItem();
    String maLop = (String) cboLop.getSelectedItem();
    String maMH = (String) cboMon.getSelectedItem();
    if (maHK == null || maLop == null || maMH == null) return;

    List<qlsv.enity.Diem> dsDiem = new qlsv.dao.impl.DiemDAOImpl().getBangDiem(maHK, maLop, maMH);
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblDiem.getModel();
    model.setRowCount(0);
    for (qlsv.enity.Diem d : dsDiem) {
        model.addRow(new Object[]{
            d.getMaSV(),
            d.getHoTen(),
            d.getMaMH(),
            d.getTenMH(),
            d.getMaHK(),
            d.getDiemLab(),
            d.getDiemQuiz(),
            d.getDiemAssignment(),
            d.getDiemFinal(),
            d.getDiemTB(),
            d.getNgayNhap(),
            false // Checkbox
        });
    }
    thongKeDiem();
}
// sự kiện khi ấn nhập điểm 
private void hienThiThongTinChiTiet() {
    fillCboMaMonChiTiet();
    fillCboHocKyChiTiet();
   int row = tblDiem.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần nhập điểm!");
        return;
    }
    // Kiểm tra đủ điểm
    Object diemLab = tblDiem.getValueAt(row, 5);
    Object diemQuiz = tblDiem.getValueAt(row, 6);
    Object diemASM = tblDiem.getValueAt(row, 7);
    Object diemFinal = tblDiem.getValueAt(row, 8);

    if (diemLab != null && diemQuiz != null && diemASM != null && diemFinal != null
        && !diemLab.toString().isEmpty() && !diemQuiz.toString().isEmpty()
        && !diemASM.toString().isEmpty() && !diemFinal.toString().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sinh viên này đã đủ điểm!");
        return; // Không hiển thị lên form
    }

    // Nếu chưa đủ điểm thì hiển thị thông tin lên form
    txtMaSV.setText(tblDiem.getValueAt(row, 0).toString());
    txtHoTen.setText(tblDiem.getValueAt(row, 1).toString());
    cboMaMon.setSelectedItem(tblDiem.getValueAt(row, 2).toString());
    txtTenMon.setText(tblDiem.getValueAt(row, 3).toString());
    cboHocKyChiTiet.setSelectedItem(tblDiem.getValueAt(row, 4).toString());

    txtDiemLab.setText(diemLab == null ? "" : diemLab.toString());
    txtDiemQuiz.setText(diemQuiz == null ? "" : diemQuiz.toString());
    txtDiemASM.setText(diemASM == null ? "" : diemASM.toString());
    txtDiemFinal.setText(diemFinal == null ? "" : diemFinal.toString());
    // ko cho chỉnh sửa 
    txtMaSV.setEditable(false);
    txtHoTen.setEditable(false);
    cboMaMon.setEnabled(false);
    txtTenMon.setEditable(false);
    cboHocKyChiTiet.setEnabled(false);
}
private void fillCboMaMonChiTiet() {
    cboMaMon.removeAllItems();
    for (int i = 0; i < cboMon.getItemCount(); i++) {
        cboMaMon.addItem(cboMon.getItemAt(i));
    }
}

private void fillCboHocKyChiTiet() {
    cboHocKyChiTiet.removeAllItems();
    for (int i = 0; i < cboHocKy.getItemCount(); i++) {
        cboHocKyChiTiet.addItem(cboHocKy.getItemAt(i));
    }
}
// HÀM LƯU 
private void luuDiem() {
    String maSV = txtMaSV.getText();
    String maMH = (String) cboMaMon.getSelectedItem();
    String maHK = (String) cboHocKyChiTiet.getSelectedItem();

    String diemLabStr = txtDiemLab.getText().trim();
    String diemQuizStr = txtDiemQuiz.getText().trim();
    String diemASMStr = txtDiemASM.getText().trim();
    String diemFinalStr = txtDiemFinal.getText().trim();
   

    boolean coDuLieu = false;
    Float diemLab = null, diemQuiz = null, diemASM = null, diemFinal = null;

    // Kiểm tra từng trường điểm
    if (!diemLabStr.isEmpty()) {
        try {
            diemLab = Float.parseFloat(diemLabStr);
            if (diemLab < 1 || diemLab > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Lab phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemQuizStr.isEmpty()) {
        try {
            diemQuiz = Float.parseFloat(diemQuizStr);
            if (diemQuiz < 1 || diemQuiz > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Quiz phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemASMStr.isEmpty()) {
        try {
            diemASM = Float.parseFloat(diemASMStr);
            if (diemASM < 1 || diemASM > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm ASM phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemFinalStr.isEmpty()) {
        try {
            diemFinal = Float.parseFloat(diemFinalStr);
            if (diemFinal < 1 || diemFinal > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Final phải là số từ 1 đến 10!");
            return;
        }
    }

    if (!coDuLieu) {
        javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin điểm nào!");
        return;
    }

    // Tạo đối tượng Diem và lưu vào database (gọi DAO)
    qlsv.enity.Diem diem = new qlsv.enity.Diem();
    diem.setMaSV(maSV);
    diem.setMaMH(maMH);
    diem.setMaHK(maHK);
    diem.setDiemLab(diemLab);
    diem.setDiemQuiz(diemQuiz);
    diem.setDiemAssignment(diemASM);
    diem.setDiemFinal(diemFinal);

    // Gọi DAO để lưu (bạn tự viết hàm insert/update trong DiemDAOImpl)
    boolean ok = new qlsv.dao.impl.DiemDAOImpl().nhapDiem(diem);
    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lưu điểm thành công!");
        tim(); // load lại bảng điểm
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Lưu điểm thất bại!");
    }
}
// HIỂN THỊ THÔNG TIN KHI SỬA ĐIỂM 
private void hienThiThongTinChiTietSua() {
    fillCboMaMonChiTiet();
    fillCboHocKyChiTiet();
    int row = tblDiem.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần sửa điểm!");
        return;
    }

    Object diemLab = tblDiem.getValueAt(row, 5);
    Object diemQuiz = tblDiem.getValueAt(row, 6);
    Object diemASM = tblDiem.getValueAt(row, 7);
    Object diemFinal = tblDiem.getValueAt(row, 8);

    // Nếu tất cả đều rỗng thì báo chưa có điểm để sửa
    boolean chuaCoDiem = (diemLab == null || diemLab.toString().isEmpty())
                      && (diemQuiz == null || diemQuiz.toString().isEmpty())
                      && (diemASM == null || diemASM.toString().isEmpty())
                      && (diemFinal == null || diemFinal.toString().isEmpty());

    if (chuaCoDiem) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sinh viên này chưa có điểm để sửa!");
        return;
    }

    // Nếu đã có ít nhất một điểm thì hiển thị lên form
    txtMaSV.setText(tblDiem.getValueAt(row, 0).toString());
    txtHoTen.setText(tblDiem.getValueAt(row, 1).toString());
    cboMaMon.setSelectedItem(tblDiem.getValueAt(row, 2).toString());
    txtTenMon.setText(tblDiem.getValueAt(row, 3).toString());
    cboHocKyChiTiet.setSelectedItem(tblDiem.getValueAt(row, 4).toString());

    txtDiemLab.setText(diemLab == null ? "" : diemLab.toString());
    txtDiemQuiz.setText(diemQuiz == null ? "" : diemQuiz.toString());
    txtDiemASM.setText(diemASM == null ? "" : diemASM.toString());
    txtDiemFinal.setText(diemFinal == null ? "" : diemFinal.toString());

    // Không cho chỉnh sửa các thông tin cơ bản
    txtMaSV.setEditable(false);
    txtHoTen.setEditable(false);
    cboMaMon.setEnabled(false);
    txtTenMon.setEditable(false);
    cboHocKyChiTiet.setEnabled(false);
}
// sửa điểm 
private void suaDiem() {
    String maSV = txtMaSV.getText();
    String maMH = (String) cboMaMon.getSelectedItem();
    String maHK = (String) cboHocKyChiTiet.getSelectedItem();

    String diemLabStr = txtDiemLab.getText().trim();
    String diemQuizStr = txtDiemQuiz.getText().trim();
    String diemASMStr = txtDiemASM.getText().trim();
    String diemFinalStr = txtDiemFinal.getText().trim();

    boolean coDuLieu = false;
    Float diemLab = null, diemQuiz = null, diemASM = null, diemFinal = null;

    // Kiểm tra từng trường điểm
    if (!diemLabStr.isEmpty()) {
        try {
            diemLab = Float.parseFloat(diemLabStr);
            if (diemLab < 1 || diemLab > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Lab phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemQuizStr.isEmpty()) {
        try {
            diemQuiz = Float.parseFloat(diemQuizStr);
            if (diemQuiz < 1 || diemQuiz > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Quiz phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemASMStr.isEmpty()) {
        try {
            diemASM = Float.parseFloat(diemASMStr);
            if (diemASM < 1 || diemASM > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm ASM phải là số từ 1 đến 10!");
            return;
        }
    }
    if (!diemFinalStr.isEmpty()) {
        try {
            diemFinal = Float.parseFloat(diemFinalStr);
            if (diemFinal < 1 || diemFinal > 10) throw new NumberFormatException();
            coDuLieu = true;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Điểm Final phải là số từ 1 đến 10!");
            return;
        }
    }

    if (!coDuLieu) {
        javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin điểm nào!");
        return;
    }

    // Tạo đối tượng Diem và gọi DAO để sửa
    qlsv.enity.Diem diem = new qlsv.enity.Diem();
    diem.setMaSV(maSV);
    diem.setMaMH(maMH);
    diem.setMaHK(maHK);
    diem.setDiemLab(diemLab);
    diem.setDiemQuiz(diemQuiz);
    diem.setDiemAssignment(diemASM);
    diem.setDiemFinal(diemFinal);

    boolean ok = new qlsv.dao.impl.DiemDAOImpl().suaDiem(diem);
    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sửa điểm thành công!");
        tim(); // load lại bảng điểm
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Sửa điểm thất bại!");
    }
}
// xóa điểm 
private void xoaDiem() {
    int row = tblDiem.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa điểm!");
        return;
    }
    String maSV = tblDiem.getValueAt(row, 0).toString();
    String maMH = tblDiem.getValueAt(row, 2).toString();
    String maHK = tblDiem.getValueAt(row, 4).toString();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa điểm của sinh viên này?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    boolean ok = new qlsv.dao.impl.DiemDAOImpl().xoaDiem(maSV, maMH, maHK);
    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa điểm thành công!");
        tim(); // load lại bảng điểm
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa điểm thất bại!");
    }
}
// thống kê 
private void thongKeDiem() {
    int tongSV = tblDiem.getRowCount();
    int dat = 0, truot = 0;
    for (int i = 0; i < tongSV; i++) {
        Object diemTBObj = tblDiem.getValueAt(i, 9); // cột Điểm TB
        if (diemTBObj != null && !diemTBObj.toString().isEmpty()) {
            try {
                float diemTB = Float.parseFloat(diemTBObj.toString());
                if (diemTB >= 5) {
                    dat++;
                } else {
                    truot++;
                }
            } catch (NumberFormatException e) {
                // bỏ qua nếu không phải số
            }
        }
    }
    lblSV.setText(String.valueOf(tongSV));
    lblDat.setText(String.valueOf(dat));
    lblTruot.setText(String.valueOf(truot));
}
}