/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import qlsv.enity.Lop;

/**
 *
 * @author ADMIN
 */
public class KhoaaDetailJDialog extends javax.swing.JDialog {

    /**
     * Creates new form KhoaaJDialog
     */
    private String maKhoa;
    private String tenKhoa;

    public KhoaaDetailJDialog(java.awt.Frame parent, boolean modal, String maKhoa, String tenKhoa) {
        super(parent, modal);
        this.maKhoa = maKhoa;
        this.tenKhoa = tenKhoa;
        initComponents();
        blbTenKhoa.setText(tenKhoa);
        loadTableLop();
        loadTableSinhVien();
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        blbTenKhoa = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSLop = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnThemLop = new javax.swing.JButton();
        btnSuaLop = new javax.swing.JButton();
        btnXoaLop = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlDSsv = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboMaSV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnThemSV2 = new javax.swing.JButton();
        btnSuaSV2 = new javax.swing.JButton();
        btnXoaSV2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý khoa - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("LIÊN KẾT CỦA KHOA : ");

        blbTenKhoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blbTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blbTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        tblDSLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp ", "Tên lớp ", "Giáo viên CN", "Niên khóa", "Sỉ số ", "Ngày bắt đầu ", "Ngày kết thúc", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDSLop);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        btnThemLop.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThemLop.setText("Thêm lớp ");
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });

        btnSuaLop.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSuaLop.setText("Sửa lớp");
        btnSuaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLopActionPerformed(evt);
            }
        });

        btnXoaLop.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoaLop.setText("Xóa lớp ");
        btnXoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaLop)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemLop)
                    .addComponent(btnSuaLop)
                    .addComponent(btnXoaLop))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Danh sách lớp thuộc khoa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Danh sách lớp ", jPanel2);

        btlDSsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số SV", "Họ tên", "Giới tính", "Địa chỉ", "SDT", "Email", "Mã lớp ", "Trạng thái", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(btlDSsv);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Danh sách sinh viên thuộc khoa ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tìm kiếm nhanh ");

        jLabel4.setText("Mã số sinh viên : ");

        cboMaSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PD", "MD", "SV" }));

        jLabel5.setText("Trạng thái : ");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang học", "Nghĩ học", "Tốt nghiệp" }));

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));

        btnThemSV2.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThemSV2.setText("Thêm sinh viên ");
        btnThemSV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        btnSuaSV2.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSuaSV2.setText("Sửa sinh viên ");
        btnSuaSV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSVActionPerformed(evt);
            }
        });

        btnXoaSV2.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoaSV2.setText("Xóa sinh viên ");
        btnXoaSV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemSV2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaSV2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaSV2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSV2)
                    .addComponent(btnSuaSV2)
                    .addComponent(btnXoaSV2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTim)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Danh sách sinh viên ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSVActionPerformed
        // TODO add your handling code here:
        xoaSinhVien();
    }//GEN-LAST:event_btnXoaSVActionPerformed

    private void btnSuaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSVActionPerformed
        // TODO add your handling code here:
        suaSinhVien();
    }//GEN-LAST:event_btnSuaSVActionPerformed

    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        // TODO add your handling code here:
        themSinhVienVaoLop();
    }//GEN-LAST:event_btnThemSVActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        timKiemSinhVien();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnXoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopActionPerformed
        // TODO add your handling code here:
        xoaLop();
    }//GEN-LAST:event_btnXoaLopActionPerformed

    private void btnSuaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLopActionPerformed
        suaLop();
    }//GEN-LAST:event_btnSuaLopActionPerformed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        KhoaThemJDialog dialog = new KhoaThemJDialog(
            (java.awt.Frame) this.getParent(),
            true,
            maKhoa
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        loadTableLop();
    }//GEN-LAST:event_btnThemLopActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaaDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaaDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaaDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaaDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhoaaDetailJDialog dialog = new KhoaaDetailJDialog(
                        new javax.swing.JFrame(),
                        true,
                        "CNTT", // mã khoa mẫu
                        "Công nghệ thông tin" // tên khoa mẫu
                );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbTenKhoa;
    private javax.swing.JTable btlDSsv;
    private javax.swing.JButton btnSuaLop;
    private javax.swing.JButton btnSuaSV2;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnThemSV2;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaLop;
    private javax.swing.JButton btnXoaSV2;
    private javax.swing.JComboBox<String> cboMaSV;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDSLop;
    // End of variables declaration//GEN-END:variables
    // đổ dữ liệu lên bảng 
    private void loadTableLop() {
        DefaultTableModel model = (DefaultTableModel) tblDSLop.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        qlsv.dao.LopDAO lopDao = new qlsv.dao.impl.LopDAOImpl();
        List<Lop> list = lopDao.selectByMaKhoa(maKhoa); // Lấy danh sách lớp theo mã khoa
        for (Lop lop : list) {
            model.addRow(new Object[]{
                lop.getMaLop(),
                lop.getTenLop(),
                lop.getMaGV(), // Hiển thị mã giáo viên chủ nhiệm
                lop.getNienKhoa(),
                lop.getSiSo(),
                lop.getNgayBatDau(),
                lop.getNgayKetThuc(),
                false // check 
            });
        }
    }

    private void suaLop() {
        // Tìm dòng nào có checkbox được chọn
        int selectedRow = -1;
        DefaultTableModel model = (DefaultTableModel) tblDSLop.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean isSelected = (Boolean) model.getValueAt(i, 7);
            if (isSelected != null && isSelected) {
                selectedRow = i;
                break;
            }
        }

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn lớp để sửa ! ",
                    "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                    return ; 
        }

        // Lấy dữ liệu trực tiếp từ bảng
        String maLopCanSua = (String) model.getValueAt(selectedRow, 0);
        String tenLop = (String) model.getValueAt(selectedRow, 1);
        String maGV = (String) model.getValueAt(selectedRow, 2);
        String nienKhoa = (String) model.getValueAt(selectedRow, 3);
        Integer siSo = (Integer) model.getValueAt(selectedRow, 4);
        java.util.Date ngayBD = (java.util.Date) model.getValueAt(selectedRow, 5);
        java.util.Date ngayKT = (java.util.Date) model.getValueAt(selectedRow, 6);

        // Tạo đối tượng Lop từ dữ liệu bảng
        Lop lop = new Lop(
                maLopCanSua, tenLop, maKhoa, "", maGV, "", nienKhoa, siSo, ngayBD, ngayKT
        );

        System.out.println("Đã tạo đối tượng Lop: " + lop.getTenLop());

        // Mở form KhoaThemJDialog ở chế độ SỬA
        KhoaThemJDialog dialog = new KhoaThemJDialog(
                (java.awt.Frame) this.getParent(),
                true,
                maKhoa,
                lop // Truyền đối tượng lớp đã tạo
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Reload lại bảng sau khi sửa xong
        loadTableLop();
    }

    // xóa lớp 
    private void xoaLop() {
        // Tìm dòng có checkbox được chọn
        int selectedRow = -1;
        DefaultTableModel model = (DefaultTableModel) tblDSLop.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean isSelected = (Boolean) model.getValueAt(i, 7);
            if (isSelected != null && isSelected) {
                selectedRow = i;
                break;
            }
        }

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn lớp cần xóa !",
                    "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin lớp
        String maLop = (String) model.getValueAt(selectedRow, 0);
        String tenLop = (String) model.getValueAt(selectedRow, 1);

        // Xác nhận xóa
        int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa lớp '" + tenLop + "'?\n\n"
                + "Hành động này không thể hoàn tác!",
                "Xác nhận xóa lớp",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (choice != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        // Thực hiện xóa (database sẽ tự kiểm tra ràng buộc)
        qlsv.dao.LopDAO dao = new qlsv.dao.impl.LopDAOImpl();
        try {
            dao.delete(maLop);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Xóa lớp thành công!",
                    "Thành công",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadTableLop(); // Reload bảng
        } catch (Exception ex) {
            // Database sẽ báo lỗi nếu không thể xóa
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không thể xóa lớp!\n\nLớp này có thể đang có sinh viên hoặc dữ liệu liên quan.",
                    "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }
// TAB CỦA DANH SÁCH SINH VIÊN NNN 

    private void loadTableSinhVien() {
        DefaultTableModel model = (DefaultTableModel) btlDSsv.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        qlsv.dao.SinhVienDAO svDao = new qlsv.dao.impl.SinhVienDAOImpl();
        qlsv.dao.LopDAO lopDao = new qlsv.dao.impl.LopDAOImpl();

        // Lấy danh sách lớp thuộc khoa này
        List<Lop> danhSachLop = lopDao.selectByMaKhoa(maKhoa);

        // Lấy tất cả sinh viên
        List<qlsv.enity.SinhVien> allSinhVien = svDao.selectAll();

        // Lọc sinh viên thuộc các lớp của khoa này
        for (qlsv.enity.SinhVien sv : allSinhVien) {
            if (sv.getMaLop() != null) {
                // Kiểm tra xem lớp của sinh viên có thuộc khoa này không
                for (Lop lop : danhSachLop) {
                    if (lop.getMaLop().equals(sv.getMaLop())) {

                        // Chuyển đổi giới tính
                        String gioiTinhStr = "Nam";
                        if (sv.getGioiTinh().equals("0") || sv.getGioiTinh().equalsIgnoreCase("false")
                                || sv.getGioiTinh().equalsIgnoreCase("nu") || sv.getGioiTinh().equalsIgnoreCase("nữ")) {
                            gioiTinhStr = "Nữ";
                        }

                        // Chuyển đổi trạng thái
                        String trangThaiStr = "Đang học";
                        if ("1".equals(sv.getTrangThai())) {
                            trangThaiStr = "Nghỉ học";
                        } else if ("2".equals(sv.getTrangThai())) {
                            trangThaiStr = "Tốt nghiệp";
                        }

                        model.addRow(new Object[]{
                            sv.getMaSV(), // Mã số SV
                            sv.getHoTen(), // Họ tên
                            gioiTinhStr, // SỬA: Sử dụng gioiTinhStr đã chuyển đổi
                            sv.getDiaChi(), // Địa chỉ
                            sv.getSdt(), // SDT
                            sv.getEmail(), // Email
                            sv.getMaLop(), // Mã lớp
                            trangThaiStr, // SỬA: Sử dụng trangThaiStr đã chuyển đổi
                            false // Checkbox
                        });
                        break; // Thoát khỏi vòng lặp lớp
                    }
                }
            }
        }
    }
    // thêm sinh viên 
    private void themSinhVienVaoLop() {
    // Lấy danh sách lớp trong khoa
    qlsv.dao.LopDAO lopDao = new qlsv.dao.impl.LopDAOImpl();
    List<Lop> danhSachLop = lopDao.selectByMaKhoa(maKhoa);
    
    if (danhSachLop.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Khoa này chưa có lớp nào!\n\n" +
            "Vui lòng tạo lớp trước khi thêm sinh viên.",
            "Thông báo",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Tạo danh sách tên lớp để hiển thị
    String[] tenCacLop = new String[danhSachLop.size()];
    for (int i = 0; i < danhSachLop.size(); i++) {
        Lop lop = danhSachLop.get(i);
        tenCacLop[i] = lop.getMaLop() + " - " + lop.getTenLop();
    }
    
    // Hiển thị dialog chọn lớp
    String lopDuocChon = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Bạn muốn thêm sinh viên vào lớp nào?\n\n" +
        "Khoa: " + tenKhoa + "\n" +
        " Vui lòng chọn lớp:",
        "Chọn lớp để thêm sinh viên",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        tenCacLop,
        tenCacLop[0] // Mặc định chọn lớp đầu tiên
    );
    
    // Nếu user không chọn lớp (Cancel)
    if (lopDuocChon == null) {
        return;
    }
    
    // Lấy mã lớp từ string được chọn (tách phần đầu trước dấu " - ")
    String maLopDuocChon = lopDuocChon.split(" - ")[0];
    
    // Tìm đối tượng Lop tương ứng
    Lop lopCanThem = null;
    for (Lop lop : danhSachLop) {
        if (lop.getMaLop().equals(maLopDuocChon)) {
            lopCanThem = lop;
            break;
        }
    }
    
    if (lopCanThem == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            " Lỗi: Không tìm thấy lớp được chọn!",
            "Lỗi",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Mở form danh sách sinh viên chưa có lớp (thay tên form của bạn vào đây)
    // Ví dụ: SinhVienChuaCoLopJDialog hoặc tên form bạn đã tạo
    try {
        // THAY ĐỔI TÊN CLASS NÀY THEO FORM CỦA BẠN
        ThemSVJDialog dialog = new ThemSVJDialog(
            (java.awt.Frame) this.getParent(),
            true,
            maLopDuocChon          // Truyền mã lớp được chọn
            
        ); 
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true); 
        
        // Sau khi đóng form thêm sinh viên, reload lại bảng
        loadTableSinhVien();
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Lỗi mở form thêm sinh viên!\n\n" +
            " Chi tiết: " + ex.getMessage(),
            "Lỗi",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
// sửa sinh viên 
private void suaSinhVien(){
    int selectedRow =-1 ; 
    DefaultTableModel model = (DefaultTableModel) btlDSsv.getModel();
    for(int i = 0 ; i < model.getRowCount() ; i ++){ 
        Boolean isSelected = (Boolean) model.getValueAt(i, 8);
        if(isSelected != null && isSelected) {
            selectedRow = i;
            break;
        }
    }
    // nếu ko chọn sinh viên nào 
    if(selectedRow == -1){
        javax.swing.JOptionPane.showMessageDialog(this,
            "Lỗi: vui lòng chọn sinh viên để sửa !",
            "Thông báo",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;

}
      // Lấy mã sinh viên từ bảng
    String maSV = (String) model.getValueAt(selectedRow, 0);        // Mã số SV
    String hoTen = (String) model.getValueAt(selectedRow, 1);       // Họ tên (để hiển thị)
    
    
    
    try {
        // Mở form sửa sinh viên (thay tên form của bạn vào đây)
        SuaSinhVienJDialog dialog = new SuaSinhVienJDialog(
            (java.awt.Frame) this.getParent(),
            true,
            maSV
           
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Sau khi đóng form sửa, reload lại bảng sinh viên
        loadTableSinhVien();
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            " Lỗi mở form sửa sinh viên!\n\n" +
            " Chi tiết: " + ex.getMessage(),
            "Lỗi",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
} 
// xóa sinh viên 
private void xoaSinhVien() {
    // Tìm dòng có checkbox được chọn
    int selectedRow = -1;
    DefaultTableModel model = (DefaultTableModel) btlDSsv.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        Boolean isSelected = (Boolean) model.getValueAt(i, 8); 
        if (isSelected != null && isSelected) {
            selectedRow = i;
            break;
        }
    }

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn sinh viên cần xóa bằng cách tick vào checkbox!",
                "Thông báo",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Lấy thông tin sinh viên từ bảng
    String maSV = (String) model.getValueAt(selectedRow, 0);
    String hoTen = (String) model.getValueAt(selectedRow, 1);
    String trangThaiStr = (String) model.getValueAt(selectedRow, 7);

    // KIỂM TRA TRẠNG THÁI - KHÔNG ĐƯỢC XÓA SINH VIÊN ĐANG HỌC
    if ("Đang học".equals(trangThaiStr)) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Không thể xóa sinh viên đang học!\n\n" +
                "Sinh viên: " + hoTen + " (Mã: " + maSV + ")\n" +
                "Trạng thái: " + trangThaiStr + "\n\n" +
                "Chỉ có thể xóa sinh viên có trạng thái 'Nghỉ học' hoặc 'Tốt nghiệp'.",
                "Không thể xóa",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Xác nhận xóa
    int choice = javax.swing.JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa sinh viên?\n\n" +
            "Họ tên: " + hoTen + "\n" +
            "Mã SV: " + maSV + "\n" +
            "Trạng thái: " + trangThaiStr + "\n\n" +
            "Cảnh báo: Hành động này không thể khôi phục !",
            "Xác nhận xóa sinh viên",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);

    if (choice != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    // Thực hiện xóa sinh viên
    qlsv.dao.SinhVienDAO dao = new qlsv.dao.impl.SinhVienDAOImpl();
    try {
        dao.delete(maSV);
        javax.swing.JOptionPane.showMessageDialog(this,
                "Xóa sinh viên thành công!\n\n" +
                "Đã xóa: " + hoTen + " (Mã: " + maSV + ")",
                "Thành công",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Reload lại bảng sinh viên
        loadTableSinhVien();
        
    } catch (Exception ex) {
        // THÔNG BÁO CHI TIẾT VỀ RÀNG BUỘC DỮ LIỆU - KHÔNG CÓ ICON
        String errorMessage = ex.getMessage().toLowerCase();
        
        if (errorMessage.contains("reference constraint") || 
            errorMessage.contains("foreign key") ||
            errorMessage.contains("fk") ||
            errorMessage.contains("conflicted") ||
            errorMessage.contains("delete statement conflicted")) {
            
            // Lỗi ràng buộc khóa ngoại - sinh viên đã có dữ liệu liên quan
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không thể xóa sinh viên!\n\n" +
                    "Sinh viên: " + hoTen + " (Mã: " + maSV + ")\n\n" +
                    "Lý do: Sinh viên này đã có dữ liệu liên quan trong hệ thống:\n" +
                    "- Điểm số trong các môn học\n" +
                    "- Dữ liệu trong bảng Diem\n" +
                    "- Hoặc các dữ liệu khác\n\n" +
                    "Giải pháp:\n" +
                    "1. Xóa tất cả điểm số của sinh viên trước\n" +
                    "2. Hoặc chuyển trạng thái thành 'Nghỉ học' thay vì xóa\n\n" +
                    "Điều này nhằm bảo vệ tính toàn vẹn dữ liệu trong hệ thống.",
                    "Không thể xóa - Có dữ liệu liên quan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            
        } else {
            // Lỗi khác
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Lỗi khi xóa sinh viên!\n\n" +
                    "Sinh viên: " + hoTen + " (Mã: " + maSV + ")\n\n" +
                    "Chi tiết lỗi: " + ex.getMessage() + "\n\n" +
                    "Vui lòng liên hệ quản trị viên nếu lỗi tiếp tục xảy ra.",
                    "Lỗi hệ thống",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        ex.printStackTrace();
    }
}
// tìm sinh viên 
// THÊM HÀM TÌM KIẾM SINH VIÊN VÀO CUỐI FILE KhoaaDetailJDialog.java
private void timKiemSinhVien() {
    DefaultTableModel model = (DefaultTableModel) btlDSsv.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    qlsv.dao.SinhVienDAO svDao = new qlsv.dao.impl.SinhVienDAOImpl();
    qlsv.dao.LopDAO lopDao = new qlsv.dao.impl.LopDAOImpl();

    // Lấy giá trị tìm kiếm từ combobox
    String maSVSearch = cboMaSV.getSelectedItem().toString().trim();
    String trangThaiSearch = cboTrangThai.getSelectedItem().toString().trim();

    // Lấy danh sách lớp thuộc khoa này
    List<Lop> danhSachLop = lopDao.selectByMaKhoa(maKhoa);

    // Lấy tất cả sinh viên
    List<qlsv.enity.SinhVien> allSinhVien = svDao.selectAll();

    // Lọc sinh viên thuộc các lớp của khoa này + điều kiện tìm kiếm
    for (qlsv.enity.SinhVien sv : allSinhVien) {
        if (sv.getMaLop() != null) {
            // Kiểm tra sinh viên thuộc khoa này
            boolean thuocKhoaNay = false;
            for (Lop lop : danhSachLop) {
                if (lop.getMaLop().equals(sv.getMaLop())) {
                    thuocKhoaNay = true;
                    break;
                }
            }
            
            if (!thuocKhoaNay) continue; // Không thuộc khoa này thì bỏ qua

            // ĐIỀU KIỆN TÌM KIẾM
            boolean khopMaSV = true;
            boolean khopTrangThai = true;

            // Tìm theo mã sinh viên (bắt đầu bằng)
            if (!"Tất cả".equals(maSVSearch)) {
                khopMaSV = sv.getMaSV().toUpperCase().startsWith(maSVSearch.toUpperCase());
            }

            // Tìm theo trạng thái
            if (!"Tất cả".equals(trangThaiSearch)) {
                String trangThaiSV = "Đang học"; // Mặc định
                if ("1".equals(sv.getTrangThai())) {
                    trangThaiSV = "Nghỉ học";
                } else if ("2".equals(sv.getTrangThai())) {
                    trangThaiSV = "Tốt nghiệp";
                }
                khopTrangThai = trangThaiSV.equals(trangThaiSearch);
            }

            // Chỉ hiển thị khi thỏa mãn tất cả điều kiện
            if (khopMaSV && khopTrangThai) {
                // Chuyển đổi giới tính
                String gioiTinhStr = "Nam";
                if (sv.getGioiTinh().equals("0") || sv.getGioiTinh().equalsIgnoreCase("false")
                        || sv.getGioiTinh().equalsIgnoreCase("nu") || sv.getGioiTinh().equalsIgnoreCase("nữ")) {
                    gioiTinhStr = "Nữ";
                }

                // Chuyển đổi trạng thái để hiển thị
                String trangThaiStr = "Đang học";
                if ("1".equals(sv.getTrangThai())) {
                    trangThaiStr = "Nghỉ học";
                } else if ("2".equals(sv.getTrangThai())) {
                    trangThaiStr = "Tốt nghiệp";
                }

                model.addRow(new Object[]{
                    sv.getMaSV(),
                    sv.getHoTen(),
                    gioiTinhStr,
                    sv.getDiaChi(),
                    sv.getSdt(),
                    sv.getEmail(),
                    sv.getMaLop(),
                    trangThaiStr,
                    false // Checkbox
                });
            }
        }
    }


    if (model.getRowCount() == 0) {
        // KHÔNG CÓ KẾT QUẢ 
        javax.swing.JOptionPane.showMessageDialog(this,
                "Không tìm thấy sinh viên nào phù hợp với điều kiện tìm kiếm!\n\n" +
                "Mã SV: " + maSVSearch + "\n" +
                "Trạng thái: " + trangThaiSearch,
                "Không có kết quả",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // SAU KHI TẮT THÔNG BÁO → LOAD LẠI TOÀN BỘ SINH VIÊN
        loadTableSinhVien();
    }
    // NẾU CÓ KẾT QUẢ → KHÔNG LÀM GÌ THÊM (đã load kết quả lên bảng rồi)
}
} 
