/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

/**
 *
 * @author ADMIN
 */
public class LopDetailJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LopDetailJDialog
     */
    public LopDetailJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadMaKhoaToComboBox();
        setLocationRelativeTo(null);

        setSize(830, 800);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());

    }

    public void setLop(qlsv.enity.Lop lop) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jTextField1.setText(lop.getMaLop());
        jTextField2.setText(lop.getTenLop());
        jTextField3.setText(lop.getMaGV());
        jTextField4.setText(lop.getNienKhoa());
        jTextField5.setText(lop.getNgayBatDau() != null ? sdf.format(lop.getNgayBatDau()) : "");
        jTextField6.setText(lop.getNgayKetThuc() != null ? sdf.format(lop.getNgayKetThuc()) : "");
        jTextField7.setText(String.valueOf(lop.getSiSo()));
        jTextField1.setEditable(false);
        // danh sách sinh viên lên bảng 
        loadSinhVienTheoLop(lop.getMaLop());
        // set dô cái combobox 
        cboKhoa.setSelectedItem(lop.getMaKhoa());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        txtNam = new javax.swing.JTextField();
        txtNu = new javax.swing.JTextField();
        btnThemSV = new javax.swing.JButton();
        btnXoaSV = new javax.swing.JButton();
        btnXoaSV1 = new javax.swing.JButton();
        btnXoaSV2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cboKhoa = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý điểm - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT LỚP HỌC");

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\CHINH.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã lớp : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Giáo viên CN : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tên lớp :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Niên khóa : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ngày bắt đầu : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ngày kết thúc : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Sỉ số : ");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        btnThem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LamMoi (1).png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\EXIT.png")); // NOI18N
        btnDong.setText("Đóng ");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số sinh viên ", "Họ và tên ", "Ngày sinh", "Giới tính", "Địa chỉ ", "SDT", "Email", "Mã lớp", "Trạng Thái", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Thống kê  nhanh ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Nam.png")); // NOI18N
        jLabel11.setText("Nam : ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Tổng sinh viên :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Nu.png")); // NOI18N
        jLabel13.setText("Nữ :");

        btnThemSV.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThemSV.setText("Thêm sinh viên ");
        btnThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        btnXoaSV.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoaSV.setText("Xóa");
        btnXoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSVActionPerformed(evt);
            }
        });

        btnXoaSV1.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnXoaSV1.setText("Sửa");
        btnXoaSV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSV1ActionPerformed(evt);
            }
        });

        btnXoaSV2.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\chuyenLop.png")); // NOI18N
        btnXoaSV2.setText("Chuyển lớp");
        btnXoaSV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSV2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Khoa : ");

        cboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "KT", "DH" }));
        cboKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Danh sách sinh viên thuộc lớp này ");

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\danhsasch.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THONGKE.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField6))
                        .addContainerGap(154, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(330, 330, 330))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThemSV)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnXoaSV1)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnXoaSV2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoaSV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDong)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa)
                        .addComponent(btnDong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSV)
                    .addComponent(btnXoaSV1)
                    .addComponent(btnXoaSV2)
                    .addComponent(btnXoaSV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        themLop();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        Sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoaLop();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        String maLop = jTextField1.getText().trim(); // hoặc lấy từ dữ liệu lớp đang chọn
        ThemSVJDialog dialog = new ThemSVJDialog((java.awt.Frame) this.getParent(), true, maLop);
        dialog.setVisible(true);
        // load lại danh sách 
         loadSinhVienTheoLop(maLop);

    }//GEN-LAST:event_btnThemSVActionPerformed

    private void btnXoaSV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSV1ActionPerformed
        // TODO add your handling code here:
        suaSinhVien();
    }//GEN-LAST:event_btnXoaSV1ActionPerformed

    private void btnXoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSVActionPerformed
        // TODO add your handling code here:
        xoaSinhVien();
    }//GEN-LAST:event_btnXoaSVActionPerformed

    private void btnXoaSV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSV2ActionPerformed
        // TODO add your handling code here:
        chuyenLopSinhVien();
    }//GEN-LAST:event_btnXoaSV2ActionPerformed

    private void cboKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaActionPerformed
        // TODO add your handling code here:
        loadMaKhoaToComboBox();
    }//GEN-LAST:event_cboKhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LopDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LopDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LopDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LopDetailJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LopDetailJDialog dialog = new LopDetailJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSV;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaSV;
    private javax.swing.JButton btnXoaSV1;
    private javax.swing.JButton btnXoaSV2;
    private javax.swing.JComboBox<String> cboKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNu;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
   

    private void loadSinhVienTheoLop(String maLop) {
        qlsv.dao.SinhVienDAO dao = new qlsv.dao.impl.SinhVienDAOImpl();
        java.util.List<qlsv.enity.SinhVien> list = dao.selectByMaLop(maLop);
        // lấy danh sách sinh viên theo mã lớp 

        // Xóa dữ liệu cũ trên bảng
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Thống kê
        int tong = 0, nam = 0, nu = 0;

        for (qlsv.enity.SinhVien sv : list) {
            // Chuyển đổi giới tính
            String gioiTinhStr = "Nam";
            if (sv.getGioiTinh().equals("0") || sv.getGioiTinh().equalsIgnoreCase("false") || sv.getGioiTinh().equalsIgnoreCase("nu") || sv.getGioiTinh().equalsIgnoreCase("nữ")) {
                gioiTinhStr = "Nữ";
                nu++;
            } else {
                nam++;
            }
            // Chuyển đổi trạng thái
            String trangThaiStr = "Đang học";
            if ("1".equals(sv.getTrangThai())) {
                trangThaiStr = "Nghỉ học";
            } else if ("2".equals(sv.getTrangThai())) {
                trangThaiStr = "Tốt nghiệp";
            }
            model.addRow(new Object[]{
                sv.getMaSV(),
                sv.getHoTen(),
                sv.getNgaySinh(),
                gioiTinhStr,
                sv.getDiaChi(),
                sv.getSdt(),
                sv.getEmail(),
                sv.getMaLop(),
                trangThaiStr,
                false
            });
            tong++;
        }

        // Hiển thị lên các ô thống kê nhanh
        txtTong.setText(String.valueOf(tong));
        txtNam.setText(String.valueOf(nam));
        txtNu.setText(String.valueOf(nu));
    }
// các nút của chức năng lớp 
// LÀM MỚI 

    private void lamMoi() {
        // Xóa dữ liệu các trường nhập thông tin lớp
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");

        // Xóa dữ liệu bảng sinh viên
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Xóa dữ liệu thống kê nhanh
        txtTong.setText("");
        txtNam.setText("");
        txtNu.setText("");

        jTextField1.setEditable(true);
    }
// THÊM LỚP 

    private void themLop() {
        String maLop = jTextField1.getText().trim();
        String tenLop = jTextField2.getText().trim();
        String maGV = jTextField3.getText().trim();
        String nienKhoa = jTextField4.getText().trim();
        String ngayBatDauStr = jTextField5.getText().trim();
        String ngayKetThucStr = jTextField6.getText().trim();
        String siSoStr = jTextField7.getText().trim();
        String maKhoa = cboKhoa.getSelectedItem() != null ? cboKhoa.getSelectedItem().toString().trim() : "";

        // Kiểm tra các trường bắt buộc
        if (maLop.isEmpty() || tenLop.isEmpty() || maGV.isEmpty() || nienKhoa.isEmpty() || ngayBatDauStr.isEmpty() || ngayKetThucStr.isEmpty() || maKhoa.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc!");
            return;
        }

        // Kiểm tra mã giáo viên có tồn tại
        qlsv.dao.NhanVienDAO nvDao = new qlsv.dao.impl.NhanVienDAOImpl();
        boolean tonTaiGV = false;
        for (qlsv.enity.NhanVien nv : nvDao.selectAll()) {
            if (nv.getMaNV().equalsIgnoreCase(maGV)) {
                tonTaiGV = true;
                break;
            }
        }
        if (!tonTaiGV) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã giáo viên này không tồn tại!");
            return;
        }

        // Kiểm tra định dạng ngày
        if (!ngayBatDauStr.matches("\\d{2}/\\d{2}/\\d{4}") || !ngayKetThucStr.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ngày bắt đầu và ngày kết thúc phải đúng định dạng dd/MM/yyyy (ví dụ: 01/01/2023)!");
            return;
        }
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        java.util.Date ngayBatDau, ngayKetThuc;
        try {
            ngayBatDau = sdf.parse(ngayBatDauStr);
            ngayKetThuc = sdf.parse(ngayKetThucStr);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày bắt đầu và ngày kết thúc phải đúng định dạng dd/MM/yyyy!");
            return;
        }

        // Kiểm tra trùng mã lớp
        qlsv.dao.LopDAO dao = new qlsv.dao.impl.LopDAOImpl();
        java.util.List<qlsv.enity.Lop> list = dao.selectAll();
        for (qlsv.enity.Lop lop : list) {
            if (lop.getMaLop().equalsIgnoreCase(maLop)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Mã lớp đã tồn tại!");
                return;
            }
        }

        // Parse sĩ số
        int siSo = 0;
        try {
            siSo = Integer.parseInt(siSoStr);
            if (siSo <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sĩ số phải là số nguyên dương!");
                return;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sĩ số phải là số nguyên dương!");
            return;
        }

        // Tạo đối tượng Lop (constructor đủ 10 tham số)
        System.out.println("Mã khoa đang chọn: [" + maKhoa + "]");
        qlsv.enity.Lop lop = new qlsv.enity.Lop(
                maLop, // String
                tenLop, // String
                maKhoa, // String maKhoa (lấy từ ComboBox)
                "", // String tenKhoa (bổ sung nếu có)
                maGV,
                "",
                nienKhoa, // String
                siSo, // int
                ngayBatDau, // Date
                ngayKetThuc // Date
        );

        // Thêm vào DB
        try {
            dao.insert(lop);
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm lớp thành công!");
            lamMoi();
            dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm lớp thất bại!\n" + ex.getMessage());
        }
    }
// Sửa lớppppppp /////////////////// 

    private void Sua() {
        String maLop = jTextField1.getText().trim();
        String tenLop = jTextField2.getText().trim();
        String maGV = jTextField3.getText().trim();
        String nienKhoa = jTextField4.getText().trim();
        String ngayBatDauStr = jTextField5.getText().trim();
        String ngayKetThucStr = jTextField6.getText().trim();
        String siSoStr = jTextField7.getText().trim();
        String maKhoa = cboKhoa.getSelectedItem() != null ? cboKhoa.getSelectedItem().toString().trim() : "";

        // Không cho sửa mã lớp (đã setEditable(false) khi setLop)
        // Kiểm tra các trường bắt buộc (trừ mã lớp)
        if (tenLop.isEmpty() || maGV.isEmpty() || nienKhoa.isEmpty() || ngayBatDauStr.isEmpty() || ngayKetThucStr.isEmpty() || maKhoa.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc!");
            return;
        }

        // Kiểm tra mã giáo viên có tồn tại
        qlsv.dao.NhanVienDAO nvDao = new qlsv.dao.impl.NhanVienDAOImpl();
        boolean tonTaiGV = false;
        for (qlsv.enity.NhanVien nv : nvDao.selectAll()) {
            if (nv.getMaNV().equalsIgnoreCase(maGV)) {
                tonTaiGV = true;
                break;
            }
        }
        if (!tonTaiGV) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã giáo viên này không tồn tại!");
            return;
        }

        // Kiểm tra định dạng ngày
        if (!ngayBatDauStr.matches("\\d{2}/\\d{2}/\\d{4}") || !ngayKetThucStr.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ngày bắt đầu và ngày kết thúc phải đúng định dạng dd/MM/yyyy (ví dụ: 01/01/2023)!");
            return;
        }
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        java.util.Date ngayBatDau, ngayKetThuc;
        try {
            ngayBatDau = sdf.parse(ngayBatDauStr);
            ngayKetThuc = sdf.parse(ngayKetThucStr);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ngày bắt đầu và ngày kết thúc không hợp lệ (ví dụ: 01/01/2023)!");
            return;
        }

        // Parse sĩ số
        int siSo = 0;
        try {
            siSo = Integer.parseInt(siSoStr);
            if (siSo <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sĩ số phải là số nguyên dương!");
                return;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sĩ số phải là số nguyên dương!");
            return;
        }

        // Tạo đối tượng Lop
        qlsv.enity.Lop lop = new qlsv.enity.Lop(
                maLop,
                tenLop,
                maKhoa,
                "",
                maGV,
                "",
                nienKhoa,
                siSo,
                ngayBatDau,
                ngayKetThuc
        );

        // Cập nhật vào DB
        qlsv.dao.LopDAO dao = new qlsv.dao.impl.LopDAOImpl();
        try {
            dao.update(lop);
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật lớp thành công!");
            dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật lớp thất bại!\n" + ex.getMessage());
        }
    }
// xóa lớp 

    private void xoaLop() {
    String maLop = jTextField1.getText().trim();
    if (maLop.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy mã lớp để xóa!");
        return;
    }

    // Kiểm tra lớp có sinh viên hoặc dữ liệu liên quan không
    qlsv.dao.SinhVienDAO svDao = new qlsv.dao.impl.SinhVienDAOImpl();
    java.util.List<qlsv.enity.SinhVien> ds = svDao.selectByMaLop(maLop);
    if (ds != null && !ds.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa lớp này vì có sinh viên hoặc dữ liệu liên quan!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa lớp này không?",
            "Xác nhận xóa",
            javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    qlsv.dao.LopDAO dao = new qlsv.dao.impl.LopDAOImpl();
    try {
        dao.delete(maLop);
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa lớp thành công!");
        dispose();
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa lớp thất bại!\n" + ex.getMessage());
    }
}

    /// sự kiện của các nút ở phía dưới 
// SỬA SINH VIÊN 
private void suaSinhVien() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên để sửa!");
            return;
        }
        // Lấy thông tin sinh viên từ bảng
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        String maSV = model.getValueAt(row, 0).toString();
        qlsv.dao.SinhVienDAO dao = new qlsv.dao.impl.SinhVienDAOImpl();
        qlsv.enity.SinhVien sv = null;
        java.util.List<qlsv.enity.SinhVien> ds = dao.selectByMaSV(maSV);
        if (ds != null && !ds.isEmpty()) {
            sv = ds.get(0);
        }

        if (sv == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin sinh viên!");
            return;
        }

        // Mở form sửa sinh viên, truyền thông tin vào
        SuaSinhVienJDialog dialog = new SuaSinhVienJDialog((java.awt.Frame) this.getParent(), true,"SV001");
        dialog.setSinhVien(sv); 
        dialog.setVisible(true);

        // Sau khi sửa xong, load lại danh sách sinh viên
        loadSinhVienTheoLop(jTextField1.getText().trim());
    }
// XÓA SINH VIÊN 

   private void xoaSinhVien() {
    int row = jTable1.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên để xóa!");
        return;
    }
    // Lấy mã sinh viên và trạng thái từ bảng
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    String maSV = model.getValueAt(row, 0).toString();
    String trangThai = model.getValueAt(row, 8).toString().trim(); // Cột 8 là trạng thái

    if ("Đang học".equalsIgnoreCase(trangThai)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa sinh viên có trạng thái 'Đang học'!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa sinh viên này không?",
            "Xác nhận xóa",
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    qlsv.dao.SinhVienDAO dao = new qlsv.dao.impl.SinhVienDAOImpl();
    try {
        dao.delete(maSV);
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!");
        loadSinhVienTheoLop(jTextField1.getText().trim());
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Xóa sinh viên thất bại!\n" + ex.getMessage());
    }
}

    // chuyển lớp 
    private void chuyenLopSinhVien() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên để chuyển lớp!");
            return;
        }
        // Lấy mã sinh viên từ bảng
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        String maSV = model.getValueAt(row, 0).toString();

        // Nhập mã lớp mới
        String maLopMoi = javax.swing.JOptionPane.showInputDialog(this, "Nhập mã lớp cần chuyển:");
        if (maLopMoi == null || maLopMoi.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã lớp mới!");
            return;
        }

        // Kiểm tra mã lớp mới có tồn tại không
        qlsv.dao.LopDAO lopDao = new qlsv.dao.impl.LopDAOImpl();
        boolean tonTaiLopMoi = false;
        for (qlsv.enity.Lop lop : lopDao.selectAll()) {
            if (lop.getMaLop().equalsIgnoreCase(maLopMoi.trim())) {
                tonTaiLopMoi = true;
                break;
            }
        }
        if (!tonTaiLopMoi) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã lớp mới không tồn tại!");
            return;
        }

        // Thực hiện chuyển lớp
        qlsv.dao.SinhVienDAO svDao = new qlsv.dao.impl.SinhVienDAOImpl();
        java.util.List<qlsv.enity.SinhVien> ds = svDao.selectByMaSV(maSV);
        if (ds != null && !ds.isEmpty()) {
            qlsv.enity.SinhVien sv = ds.get(0);
            sv.setMaLop(maLopMoi.trim());
            try {
                svDao.update(sv);
                javax.swing.JOptionPane.showMessageDialog(this, "Chuyển lớp thành công!");
                loadSinhVienTheoLop(jTextField1.getText().trim());
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Chuyển lớp thất bại!\n" + ex.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên để chuyển lớp!");
        }
    }
// CỦA CBO 
private void loadMaKhoaToComboBox() {
    cboKhoa.removeAllItems();
    qlsv.dao.KhoaDAO khoaDao = new qlsv.dao.impl.KhoaDAOImpl();
    for (qlsv.enity.Khoa k : khoaDao.selectAll()) {
        cboKhoa.addItem(k.getMaKhoa());
    }
    // Đảm bảo luôn chọn 1 mã khoa mặc định nếu có
    if (cboKhoa.getItemCount() > 0) {
        cboKhoa.setSelectedIndex(0);
    }
    cboKhoa.setEditable(false);
}
}
