/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class LopJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LopJDialog
     */
    public LopJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillCardsLop();
        setLocationRelativeTo(null); // Căn giữa
        setSize(700, 500); 
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

    pnlCards = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(pnlCards); // Đúng

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    pnlCards.setLayout(new java.awt.GridLayout(0, 3, 6, 3));

    jPanel1.setBackground(new java.awt.Color(102, 102, 255));
    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Quản lý lớp");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jLabel1)
            .addContainerGap(23, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // <-- dùng scrollPane thay pnlCards
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE) // <-- dùng scrollPane thay pnlCards
            .addContainerGap())
    );

    pack();
}
    private void pnlCardsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCardsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlCardsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LopJDialog dialog = new LopJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCards;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
    private void fillCardsLop() {
        // xóa tất cả carld củ tren panel 
    pnlCards.removeAll();
    qlsv.dao.LopDAO dao = new qlsv.dao.impl.LopDAOImpl();// tạo đối tượng rồi lấy toàn bộ danh sách 
    java.util.List<qlsv.enity.Lop> list = dao.selectAll();
    for (qlsv.enity.Lop lop : list) {
        JPanel card = new JPanel();// tạo một cái jpanel cho mỗi lớp 
        card.setPreferredSize(new java.awt.Dimension(200, 200));
        card.setBackground(java.awt.Color.WHITE);// thiết lập màu nền 
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2),// thiết lập đường viền
            javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12)// thiết lập khoảng cách
        ));
        card.setLayout(new java.awt.GridLayout(4, 1, 0, 2));

        JLabel lblMaLop = new JLabel(" Mã lớp: " + lop.getMaLop());
        lblMaLop.setFont(lblMaLop.getFont().deriveFont(java.awt.Font.BOLD, 14f));
        
        card.add(lblMaLop);

        JLabel lblTenLop = new JLabel("Tên: " + lop.getTenLop());
        lblTenLop.setFont(lblTenLop.getFont().deriveFont(java.awt.Font.PLAIN, 13f));
        card.add(lblTenLop);

        JLabel lblGV = new JLabel("GV: " + lop.getMaGV());
        lblGV.setFont(lblGV.getFont().deriveFont(java.awt.Font.PLAIN, 13f));
        card.add(lblGV);

        JLabel lblSiSo = new JLabel("Sĩ số: " + lop.getSiSo());
        lblSiSo.setFont(lblSiSo.getFont().deriveFont(java.awt.Font.PLAIN, 13f));
        card.add(lblSiSo);// hiển thị thông tin của lớp lên card 

        // Hiệu ứng hover
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card.setBackground(new java.awt.Color(204, 232, 255));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card.setBackground(java.awt.Color.WHITE);
            }
             public void mouseClicked(java.awt.event.MouseEvent evt) {
            // Mở form chi tiết lớp khi click vào card
            LopDetailJDialog dialog = new LopDetailJDialog((java.awt.Frame) getParent(), true);
            dialog.setLop(lop);
            dialog.setVisible(true);
            fillCardsLop();
        }
        });

        pnlCards.add(card);
    }
    pnlCards.revalidate();
    pnlCards.repaint();
}

}
