/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import java.sql.Date;
import qlsv.dao.NhanVienDAO;
import qlsv.dao.impl.NhanVienDAOImpl;
import qlsv.enity.NhanVien;

/**
 *
 * @author ADMIN
 */
public class NhanVienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NhanVienJDialog
     */
    public NhanVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillTableNhanVien();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangNV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnALL = new javax.swing.JButton();
        btnUNALL = new javax.swing.JButton();
        btndeleteALL = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        rdGiaoVien = new javax.swing.JRadioButton();
        rdQuanTri = new javax.swing.JRadioButton();
        rdHoatDong = new javax.swing.JRadioButton();
        rdNgungHD = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhân viên - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN ");

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\CHINH.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tblBangNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên ", "Mật khẩu", "Họ tên ", "Email", "Số điện thoại", "Giới tính", "Địa chỉ", "Vai trò", "Ngày tạo", "Trạng thái", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangNV);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên : ");

        btnTim.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\tim.png")); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnLoad.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LOADLAINE.png")); // NOI18N
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnALL.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\chonTatCa.png")); // NOI18N
        btnALL.setText("Chọn tất cả ");
        btnALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALLActionPerformed(evt);
            }
        });

        btnUNALL.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\BOCHONTATCA.png")); // NOI18N
        btnUNALL.setText("Bỏ chọn tất cả ");
        btnUNALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUNALLActionPerformed(evt);
            }
        });

        btndeleteALL.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btndeleteALL.setText("Xóa các mục đã chọn ");
        btndeleteALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnALL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUNALL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeleteALL)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnLoad)
                    .addComponent(btnALL)
                    .addComponent(btnUNALL)
                    .addComponent(btndeleteALL))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã nhân viên : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày tạo : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mật khẩu :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Họ tên : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Vai trò : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Giới tính : ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Trạng thái: ");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        buttonGroup1.add(rdGiaoVien);
        rdGiaoVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdGiaoVien.setText("Giáo viên ");
        rdGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGiaoVienActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdQuanTri);
        rdQuanTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdQuanTri.setText("Quản trị ");

        buttonGroup2.add(rdHoatDong);
        rdHoatDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdHoatDong.setText("Hoạt động ");

        buttonGroup2.add(rdNgungHD);
        rdNgungHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdNgungHD.setText("Ngừng hoạt động ");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));

        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LamMoi (1).png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoa.setText("xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSua.setText("sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThem))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(rdQuanTri, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(rdNgungHD)
                                        .addContainerGap())))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rdHoatDong)
                            .addComponent(rdNgungHD)
                            .addComponent(jLabel4)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdQuanTri)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(rdGiaoVien)
                                .addComponent(jLabel6)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Biểu mẫu", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGiaoVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdGiaoVienActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        timNhanVienByMa();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        fillTableNhanVien();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALLActionPerformed
        // TODO add your handling code here:
        chonTatCa();
    }//GEN-LAST:event_btnALLActionPerformed

    private void btnUNALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUNALLActionPerformed
        // TODO add your handling code here:
        boTatCa();
    }//GEN-LAST:event_btnUNALLActionPerformed

    private void btndeleteALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteALLActionPerformed
        // TODO add your handling code here:
        xoaCacMucDaChon();
    }//GEN-LAST:event_btndeleteALLActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblBangNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangNVMouseClicked
        // TODO add your handling code here:
       int row = tblBangNV.getSelectedRow();
    if (evt.getClickCount() == 2 && row != -1) {
        Object maNV = tblBangNV.getValueAt(row, 0);
        Object matKhau = tblBangNV.getValueAt(row, 1);
        Object hoTen = tblBangNV.getValueAt(row, 2);
        Object email = tblBangNV.getValueAt(row, 3);
        Object sdt = tblBangNV.getValueAt(row, 4);
        Object gioiTinh = tblBangNV.getValueAt(row, 5);
        Object diaChi = tblBangNV.getValueAt(row, 6);
        Object vaiTro = tblBangNV.getValueAt(row, 7);
        Object ngayTao = tblBangNV.getValueAt(row, 8);
        Object trangThai = tblBangNV.getValueAt(row, 9);

        txtMaNV.setText(maNV != null ? maNV.toString() : "");
        txtMatKhau.setText(matKhau != null ? matKhau.toString() : "");
        txtHoTen.setText(hoTen != null ? hoTen.toString() : "");
        txtEmail.setText(email != null ? email.toString() : "");
        txtSDT.setText(sdt != null ? sdt.toString() : "");
        cboGioiTinh.setSelectedItem(gioiTinh != null ? gioiTinh.toString() : "");
        txtDiaChi.setText(diaChi != null ? diaChi.toString() : "");
        if (vaiTro != null && "Quản trị".equalsIgnoreCase(vaiTro.toString())) {
            rdQuanTri.setSelected(true);
        } else {
            rdGiaoVien.setSelected(true);
        }
        txtNgayTao.setText(ngayTao != null ? ngayTao.toString() : "");
        if (trangThai != null && "Hoạt động".equalsIgnoreCase(trangThai.toString())) {
            rdHoatDong.setSelected(true);
        } else {
            rdNgungHD.setSelected(true);
        }
        jTabbedPane1.setSelectedIndex(1); // Chuyển sang tab Biểu mẫu
        txtMaNV.setEnabled(false);
        txtMaNV.setEditable(false);
    }
    }//GEN-LAST:event_tblBangNVMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhanVienJDialog dialog = new NhanVienJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnALL;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnUNALL;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btndeleteALL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdGiaoVien;
    private javax.swing.JRadioButton rdHoatDong;
    private javax.swing.JRadioButton rdNgungHD;
    private javax.swing.JRadioButton rdQuanTri;
    private javax.swing.JTable tblBangNV;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
    // dữ liệu lên bảng 
    private void fillTableNhanVien() {
    NhanVienDAO dao = new NhanVienDAOImpl();// tạo đối tuọng dao để truy xuất dữ liệu 
    java.util.List<NhanVien> list = dao.selectAll();
    // lấy model của bảng và xóa hết dữ liệu củ lên bảng 
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBangNV.getModel();
    model.setRowCount(0);
    // duyệt qua từng nhân viên 
    for (NhanVien nv : list) {
        model.addRow(new Object[]{
            nv.getMaNV(),
            nv.getMatKhau(),
            nv.getHoTen(),
            nv.getEmail(),
            nv.getSdt(),
            nv.getGioiTinh() ? "Nam" : "Nữ",
            nv.getDiaChi(),
            nv.getVaiTro() ? "Quản trị" : "Giáo viên",
            nv.getNgayTao(),
            nv.getTrangThai() ? "Hoạt động" : "Ngừng hoạt động",
            false // Checkbox
        });
    }
}
// tìm nè 
private void timNhanVienByMa() {
    // lấy mã nhân viên từ ô nhập 
    String maNV = txtTim.getText().trim();
    // rỗng thi thông báo rồi dừng luôn 
    if (maNV.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên cần tìm!");
        return;
    }
    // tạo đối tượng để truy xuất dữ liệu 
    NhanVienDAO dao = new NhanVienDAOImpl();
    NhanVien nv = dao.findById(maNV);
    // chuẩn bị bảng để hiển thị kết quả 
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBangNV.getModel();
    model.setRowCount(0);
    // nếu tìm thấy thì hiển thị kết quả lên bảng 
    if (nv != null) {
        model.addRow(new Object[]{
            nv.getMaNV(),
            nv.getMatKhau(),
            nv.getHoTen(),
            nv.getEmail(),
            nv.getSdt(),
            nv.getGioiTinh() ? "Nam" : "Nữ",
            nv.getDiaChi(),
            nv.getVaiTro() ? "Quản trị" : "Giáo viên",
            nv.getNgayTao(),
            nv.getTrangThai() ? "Hoạt động" : "Ngừng hoạt động",
            false // Checkbox
        });
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên với mã: " + maNV);
    }
}
// chọn tất cả 
private void chonTatCa() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBangNV.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        model.setValueAt(true, i, model.getColumnCount() - 1); // Cột cuối là checkbox
    }
}
// bỏ 
private void boTatCa() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBangNV.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        model.setValueAt(false, i, model.getColumnCount() - 1); // Cột cuối là checkbox
    }
}
// xóa các mục 
private void xoaCacMucDaChon() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBangNV.getModel();
    NhanVienDAO dao = new NhanVienDAOImpl();
    // duyệt từ cuối lên đầu để tránh xóa nhầm hàng 
    for (int i = model.getRowCount() - 1; i >= 0; i--) {
        Boolean checked = (Boolean) model.getValueAt(i, model.getColumnCount() - 1);
        // nếu check box ở cuối là true thì thì thực hiện xóa 
        if (checked != null && checked) {
            String maNV = (String) model.getValueAt(i, 0); // Cột 0 là mã nhân viên
            String vaiTro = (String) model.getValueAt(i, 7); // Cột 7 là vai trò
            if ("Quản trị".equalsIgnoreCase(vaiTro) || "Quản trị viên".equalsIgnoreCase(vaiTro)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa tài khoản quản trị: " + maNV);
                continue;
            }
            dao.delete(maNV);// gọi dao để xóa khỏi database 
            model.removeRow(i);// xóa dòng khỏi giaodienj 
        }
    }
}
// sửa 
private void sua() {
    int row = tblBangNV.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
        return;
    }
    // Kiểm tra thông tin không được rỗng
    if (txtMaNV.getText().trim().isEmpty() ||
        txtMatKhau.getText().trim().isEmpty() ||
        txtHoTen.getText().trim().isEmpty() ||
        txtEmail.getText().trim().isEmpty() ||
        txtSDT.getText().trim().isEmpty() ||
        txtDiaChi.getText().trim().isEmpty() ||
        txtNgayTao.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không được để trống thông tin!");
        return;
    }
    // Chuyển đổi ngày tạo từ String sang java.sql.Date
    Date ngayTao;
    try {
        ngayTao = Date.valueOf(txtNgayTao.getText().trim()); // Định dạng yyyy-MM-dd
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ngày tạo không đúng định dạng (Năm-Tháng-Ngày)!");
        return;
    }

    // Tạo đối tượng nhân viên
    NhanVien nv = new NhanVien();
    nv.setMaNV(txtMaNV.getText().trim());
    nv.setMatKhau(txtMatKhau.getText().trim());
    nv.setHoTen(txtHoTen.getText().trim());
    nv.setEmail(txtEmail.getText().trim());
    nv.setSdt(txtSDT.getText().trim());
    nv.setDiaChi(txtDiaChi.getText().trim());
    nv.setNgayTao(ngayTao); // Đúng kiểu java.sql.Date
    nv.setGioiTinh("Nam".equals(cboGioiTinh.getSelectedItem()));
    nv.setVaiTro(rdQuanTri.isSelected());
    nv.setTrangThai(rdHoatDong.isSelected());

    NhanVienDAO dao = new NhanVienDAOImpl();
    dao.update(nv);// gọi dao để cập nhật trên database 
    fillTableNhanVien();
    javax.swing.JOptionPane.showMessageDialog(this, "Sửa thông tin nhân viên thành công!");
    lamMoi();
}
private void lamMoi() {
    txtMaNV.setText("");
    txtMaNV.setEnabled(true);
    txtMaNV.setEditable(true);
    txtMatKhau.setText("");
    txtHoTen.setText("");
    txtEmail.setText("");
    txtSDT.setText("");
    txtDiaChi.setText("");
    txtNgayTao.setText("");
    cboGioiTinh.setSelectedIndex(0); // Mặc định là "Nam"
    rdGiaoVien.setSelected(true);    // Mặc định là Giáo viên
    rdHoatDong.setSelected(true);    // Mặc định là Hoạt động
    tblBangNV.clearSelection();      // Bỏ chọn trên bảng
}
private void them() {
    // Kiểm tra thông tin không được rỗng
    if (txtMaNV.getText().trim().isEmpty() ||
        txtMatKhau.getText().trim().isEmpty() ||
        txtHoTen.getText().trim().isEmpty() ||
        txtEmail.getText().trim().isEmpty() ||
        txtSDT.getText().trim().isEmpty() ||
        txtDiaChi.getText().trim().isEmpty() ||
        txtNgayTao.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không được để trống thông tin!");
        return;
    }
    // Kiểm tra trùng mã nhân viên
    NhanVienDAO dao = new NhanVienDAOImpl();
    if (dao.findById(txtMaNV.getText().trim()) != null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
        return;
    }
    // Chuyển đổi ngày tạo từ String sang java.sql.Date (dd/MM/yyyy)
    java.sql.Date ngayTao;
    try {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
        java.util.Date utilDate = sdf.parse(txtNgayTao.getText().trim());
        ngayTao = new java.sql.Date(utilDate.getTime());
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ngày tạo không đúng định dạng (Ngày-Tháng-Năm)!");
        return;
    }

    // Tạo đối tượng nhân viên
    NhanVien nv = new NhanVien();
    nv.setMaNV(txtMaNV.getText().trim());
    nv.setMatKhau(txtMatKhau.getText().trim());
    nv.setHoTen(txtHoTen.getText().trim());
    nv.setEmail(txtEmail.getText().trim());
    nv.setSdt(txtSDT.getText().trim());
    nv.setDiaChi(txtDiaChi.getText().trim());
    nv.setNgayTao(ngayTao);
    nv.setGioiTinh("Nam".equals(cboGioiTinh.getSelectedItem()));
    nv.setVaiTro(rdQuanTri.isSelected());
    nv.setTrangThai(rdHoatDong.isSelected());
    lamMoi();

    if (dao.insert(nv)) {
        fillTableNhanVien();
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
        lamMoi();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại!");
    }
}
private void xoa() {
    int row = tblBangNV.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
        return;
    }
    String trangThai = tblBangNV.getValueAt(row, 9).toString().trim(); // Cột 9 là trạng thái
    if ("Hoạt động".equalsIgnoreCase(trangThai)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa nhân viên đang hoạt động!");
        return;
    }
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn xóa nhân viên này?",
        "Xác nhận xóa",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }
    String maNV = tblBangNV.getValueAt(row, 0).toString();
    NhanVienDAO dao = new NhanVienDAOImpl();
    dao.delete(maNV);
    fillTableNhanVien();
    javax.swing.JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
    lamMoi();
}
}
