/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsv.ui;

import java.awt.Color;
import static java.awt.Color.white;

/**
 *
 * @author ADMIN
 */
public class QlsvJFrame extends javax.swing.JFrame {

    /**
     * Creates new form QlsvJFrame
     */
    public QlsvJFrame() {
        initComponents();
        // Hiển thị tên và vai trò
        setLocationRelativeTo(null);// in ra giữa màn hình 
        if (qlsv.util.Auth.user != null) {
            lblXinChao.setText(qlsv.util.Auth.user.getHoTen());
            lblVaiTro.setText(qlsv.util.Auth.user.getVaiTroText());
        }

        // Ẩn nút nếu là nhân viên thường
        if (!qlsv.util.Auth.user.getVaiTro()) {
            btnTaiKhoan.setVisible(false);
            btnThongKe.setVisible(false);
        }
        // icon của menue bar 
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnSinhVien = new javax.swing.JButton();
        btnHocKy = new javax.swing.JButton();
        btnDiem = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnKhoa = new javax.swing.JButton();
        btnLop = new javax.swing.JButton();
        btnMonHoc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblXinChao = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuDX = new javax.swing.JMenuItem();
        MenuDMK = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý sinh viên - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ SINH VIÊN ");

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\icons8-graduation-cap-100.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        BtnSinhVien.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\sinhvien.png")); // NOI18N
        BtnSinhVien.setText("Sinh viên ");
        BtnSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSinhVienMouseExited(evt);
            }
        });
        BtnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSinhVienActionPerformed(evt);
            }
        });

        btnHocKy.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\HOCKY.png")); // NOI18N
        btnHocKy.setText("Học kỳ");
        btnHocKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHocKyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHocKyMouseExited(evt);
            }
        });
        btnHocKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocKyActionPerformed(evt);
            }
        });

        btnDiem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\DIEM.png")); // NOI18N
        btnDiem.setText("Điểm ");
        btnDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiemMouseExited(evt);
            }
        });
        btnDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemActionPerformed(evt);
            }
        });

        btnThongKe.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THONGKE.png")); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnTaiKhoan.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\TAIKHOAN.png")); // NOI18N
        btnTaiKhoan.setText("Tài Khoản ");
        btnTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseExited(evt);
            }
        });
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnKhoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\KHOA.png")); // NOI18N
        btnKhoa.setText("Khoa ");
        btnKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhoaMouseExited(evt);
            }
        });
        btnKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaActionPerformed(evt);
            }
        });

        btnLop.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LOP.png")); // NOI18N
        btnLop.setText("Lớp");
        btnLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLopMouseExited(evt);
            }
        });
        btnLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopActionPerformed(evt);
            }
        });

        btnMonHoc.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\MONHOC.png")); // NOI18N
        btnMonHoc.setText("Môn học");
        btnMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonHocMouseExited(evt);
            }
        });
        btnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHocKy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoa)
                    .addComponent(btnLop)
                    .addComponent(btnMonHoc)
                    .addComponent(btnThongKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSinhVien)
                    .addComponent(btnDiem)
                    .addComponent(btnHocKy)
                    .addComponent(btnTaiKhoan))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        lblXinChao.setText("Nguyễn Phi Thông ");

        lblVaiTro.setText("Quản lý ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("\"Nâng tầm tri thức  - Vững bước tương lai \"");

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\SACHHHHHH.gif")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\TenLUA.gif")); // NOI18N

        jLabel3.setText("Vai Trò : ");

        jLabel2.setText("Xin Chào : ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-admin-30.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\icons8-hello-24.png")); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Menu.png")); // NOI18N

        MenuDX.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MenuDX.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\ĐangNhapppppp.png")); // NOI18N
        MenuDX.setText("Đăng xuất ");
        MenuDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDXActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDX);

        MenuDMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuDMK.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\doimatKHAU.png")); // NOI18N
        MenuDMK.setText("Đổi mật khẩu");
        MenuDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDMKActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDMK);
        jMenu1.add(jSeparator2);

        MenuThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuThoat.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\EXIT.png")); // NOI18N
        MenuThoat.setText("Thoát");
        MenuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuThoatActionPerformed(evt);
            }
        });
        jMenu1.add(MenuThoat);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 44, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblXinChao)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3)
                                            .addComponent(lblVaiTro))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDXActionPerformed
        this.dispose(); // Đóng cửa sổ chính
        LoginJDialog login = new LoginJDialog(null, true);
        login.setVisible(true);
        // Nếu đăng nhập thành công (Auth.user != null), mở lại cửa sổ chính
        if (qlsv.util.Auth.user != null) {
            new QlsvJFrame().setVisible(true);
        }

    }//GEN-LAST:event_MenuDXActionPerformed

    private void BtnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSinhVienActionPerformed
        // TODO add your handling code here:
        SinhVienJDialog dialog = new SinhVienJDialog(this, true); // 'this' là JFrame cha
        dialog.setLocationRelativeTo(this); // căn giữa cửa sổ
        dialog.setVisible(true); // hiển thị dialog
    }//GEN-LAST:event_BtnSinhVienActionPerformed

    private void btnKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaActionPerformed
        // TODO add your handling code here:
        KhoaJDialog dialog = new KhoaJDialog(this, true); // truyền this là JFrame cha, true là modal
        dialog.setVisible(true);
    }//GEN-LAST:event_btnKhoaActionPerformed

    private void btnLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopActionPerformed
        // TODO add your handling code here:
        LopJDialog dialog = new LopJDialog((java.awt.Frame) this.getParent(), true);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnLopActionPerformed

    private void btnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonHocActionPerformed
        // TODO add your handling code here:
        MonHocJDialog dialog = new MonHocJDialog(this, true);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnMonHocActionPerformed

    private void btnKhoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaMouseEntered
        // TODO add your handling code here:
        btnKhoa.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnKhoaMouseEntered

    private void btnKhoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaMouseExited
        // TODO add your handling code here:
        btnKhoa.setBackground(Color.white);
    }//GEN-LAST:event_btnKhoaMouseExited

    private void btnLopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLopMouseEntered
        // TODO add your handling code here:
        btnLop.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnLopMouseEntered

    private void btnLopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLopMouseExited
        // TODO add your handling code here:
        btnLop.setBackground(white);
    }//GEN-LAST:event_btnLopMouseExited

    private void btnMonHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonHocMouseEntered
        // TODO add your handling code here:
        btnMonHoc.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnMonHocMouseEntered

    private void btnMonHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonHocMouseExited
        // TODO add your handling code here:
        btnMonHoc.setBackground(white);
    }//GEN-LAST:event_btnMonHocMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        // TODO add your handling code here:
        btnThongKe.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        // TODO add your handling code here:
        btnThongKe.setBackground(white);
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnHocKyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocKyMouseEntered
        // TODO add your handling code here:
        btnHocKy.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnHocKyMouseEntered

    private void btnHocKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocKyMouseExited
        // TODO add your handling code here:
        btnHocKy.setBackground(white);
    }//GEN-LAST:event_btnHocKyMouseExited

    private void btnDiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiemMouseEntered
        // TODO add your handling code here:
        btnDiem.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnDiemMouseEntered

    private void btnDiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiemMouseExited
        // TODO add your handling code here:
        btnDiem.setBackground(white);
    }//GEN-LAST:event_btnDiemMouseExited

    private void BtnSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSinhVienMouseEntered
        // TODO add your handling code here:
        BtnSinhVien.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_BtnSinhVienMouseEntered

    private void BtnSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSinhVienMouseExited
        // TODO add your handling code here:
        BtnSinhVien.setBackground(white);
    }//GEN-LAST:event_BtnSinhVienMouseExited

    private void btnTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseEntered
        // TODO add your handling code here:
        btnTaiKhoan.setBackground(new Color(100, 181, 246));
    }//GEN-LAST:event_btnTaiKhoanMouseEntered

    private void btnTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseExited
        // TODO add your handling code here:
        btnTaiKhoan.setBackground(white);
    }//GEN-LAST:event_btnTaiKhoanMouseExited

    private void MenuDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDMKActionPerformed
        // TODO add your handling code here:
        new qlsv.ui.DoiMatKhauJDilog(this, true).setVisible(true);
    }//GEN-LAST:event_MenuDMKActionPerformed

    private void MenuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuThoatActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        NhanVienJDialog dialog = new NhanVienJDialog(this, true); // this là JFrame cha, true là modal
        dialog.setLocationRelativeTo(this); // căn giữa cửa sổ cha
        dialog.setVisible(true);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnHocKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocKyActionPerformed
        // TODO add your handling code here:
        HocKyJDialog dialog = new HocKyJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnHocKyActionPerformed

    private void btnDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemActionPerformed
        // TODO add your handling code here:
        DiemJDialog dialog = new DiemJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnDiemActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        ThongKeJDialog dialog = new ThongKeJDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QlsvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QlsvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QlsvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QlsvJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QlsvJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSinhVien;
    private javax.swing.JMenuItem MenuDMK;
    private javax.swing.JMenuItem MenuDX;
    private javax.swing.JMenuItem MenuThoat;
    private javax.swing.JButton btnDiem;
    private javax.swing.JButton btnHocKy;
    private javax.swing.JButton btnKhoa;
    private javax.swing.JButton btnLop;
    private javax.swing.JButton btnMonHoc;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JLabel lblXinChao;
    // End of variables declaration//GEN-END:variables
}
