/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import java.awt.Color;
import static java.awt.Color.white;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import qlsv.dao.SinhVienDAO;
import qlsv.dao.impl.SinhVienDAOImpl;
import qlsv.enity.SinhVien;

/**
 *
 * @author ADMIN
 */
public class SinhVienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form SinhVienJDialog
     */
    public SinhVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillTableSinhVien(); // Đổ dữ liệu lên bảng
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnXoaDaChon = new javax.swing.JButton();
        btnChonTatCa = new javax.swing.JButton();
        btnBoChonTatCa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTimMaSv = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSv = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgSinh = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        cboTrangThai = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sinh viên -Nguyễn Phi Thông ");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ SINH VIÊN ");

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\CHINH.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Danh sách sinh viên ");

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên ", "Họ tên", "Ngày sinh ", "Giới tính ", "Địa chỉ ", "SDT", "Email", "Mã lớp ", "Trạng thái", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        btnXoaDaChon.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoaDaChon.setText("Xóa các mục đã chọn ");
        btnXoaDaChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaDaChonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaDaChonMouseExited(evt);
            }
        });
        btnXoaDaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDaChonActionPerformed(evt);
            }
        });

        btnChonTatCa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\chonTatCa.png")); // NOI18N
        btnChonTatCa.setText("Chọn tất cả ");
        btnChonTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChonTatCaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChonTatCaMouseExited(evt);
            }
        });
        btnChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTatCaActionPerformed(evt);
            }
        });

        btnBoChonTatCa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\BOCHONTATCA.png")); // NOI18N
        btnBoChonTatCa.setText("Bỏ chọn tất cả ");
        btnBoChonTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBoChonTatCaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBoChonTatCaMouseExited(evt);
            }
        });
        btnBoChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoChonTatCaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mã sinh viên : ");

        btnTimKiem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Tim.png")); // NOI18N
        btnTimKiem.setText("Tìm kiếm ");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseExited(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLoad.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LOADLAINE.png")); // NOI18N
        btnLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadMouseExited(evt);
            }
        });
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChonTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBoChonTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaDaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaDaChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBoChonTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonTatCa))
                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTimMaSv)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách ", jPanel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã sinh viên : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Email : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Trạng thái : ");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang học", "Nghĩ học ", "Tốt nghiệp" }));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSua.setText("Sửa ");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LamMoi (1).png")); // NOI18N
        btnLamMoi.setText("Làm mới ");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseExited(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(26, 26, 26)
                .addComponent(btnLamMoi)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Mã lớp : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaLop))))))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Biểu mẫu ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        String maSV = txtTimMaSv.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0);
        SinhVienDAO dao = new SinhVienDAOImpl();
        List<SinhVien> list;
        if (maSV.isEmpty()) {
            list = dao.selectAll();
        } else {
            list = dao.selectByMaSV(maSV);
        }
        if (list.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên!");
            return;
        }
        for (SinhVien sv : list) {
            String trangThaiText;
            switch (sv.getTrangThai()) {
                case "0":
                    trangThaiText = "Đang học";
                    break;
                case "1":
                    trangThaiText = "Nghỉ học";
                    break;
                case "2":
                    trangThaiText = "Tốt nghiệp";
                    break;
                default:
                    trangThaiText = "Không xác định";
            }
            String gioiTinhText = "0".equals(sv.getGioiTinh()) ? "Nữ" : "Nam";
            model.addRow(new Object[]{
                sv.getMaSV(),
                sv.getHoTen(),
                sv.getNgaySinh(),
                gioiTinhText,
                sv.getDiaChi(),
                sv.getSdt(),
                sv.getEmail(),
                sv.getMaLop(),
                trangThaiText,
                false
            });
        }
    }

    private void btnChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTatCaActionPerformed
        // TODO add your handling code here:
        this.checkAll();
    }//GEN-LAST:event_btnChonTatCaActionPerformed

    private void btnBoChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoChonTatCaActionPerformed
        // TODO add your handling code here:
        boChonTatCa();
    }//GEN-LAST:event_btnBoChonTatCaActionPerformed

    private void btnXoaDaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDaChonActionPerformed
        // TODO add your handling code here:
        xoaDaChon();

    }//GEN-LAST:event_btnXoaDaChonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        sua(); 
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoiForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        fillTableSinhVien();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseEntered
        // TODO add your handling code here:
        btnTimKiem.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnTimKiemMouseEntered

    private void btnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseExited
        // TODO add your handling code here:
        btnTimKiem.setBackground(white);
    }//GEN-LAST:event_btnTimKiemMouseExited

    private void btnLoadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseEntered
        // TODO add your handling code here:
        btnLoad.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnLoadMouseEntered

    private void btnLoadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseExited
        // TODO add your handling code here:
        btnLoad.setBackground(white);
    }//GEN-LAST:event_btnLoadMouseExited

    private void btnChonTatCaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonTatCaMouseEntered
        // TODO add your handling code here:
        btnChonTatCa.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnChonTatCaMouseEntered

    private void btnChonTatCaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonTatCaMouseExited
        // TODO add your handling code here:
        btnChonTatCa.setBackground(white);
    }//GEN-LAST:event_btnChonTatCaMouseExited

    private void btnBoChonTatCaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoChonTatCaMouseEntered
        // TODO add your handling code here:
        btnBoChonTatCa.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnBoChonTatCaMouseEntered

    private void btnBoChonTatCaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoChonTatCaMouseExited
        // TODO add your handling code here:
        btnBoChonTatCa.setBackground(white);
    }//GEN-LAST:event_btnBoChonTatCaMouseExited

    private void btnXoaDaChonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaDaChonMouseEntered
        // TODO add your handling code here:
        btnXoaDaChon.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnXoaDaChonMouseEntered

    private void btnXoaDaChonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaDaChonMouseExited
        // TODO add your handling code here:
        btnXoaDaChon.setBackground(white);
    }//GEN-LAST:event_btnXoaDaChonMouseExited

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        // TODO add your handling code here:
        btnThem.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        // TODO add your handling code here:
        btnThem.setBackground(white);
    }//GEN-LAST:event_btnThemMouseExited

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        // TODO add your handling code here:
        btnSua.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        // TODO add your handling code here:
        btnSua.setBackground(white);
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        // TODO add your handling code here:
        btnXoa.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        // TODO add your handling code here:
        btnXoa.setBackground(white);
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseEntered
        // TODO add your handling code here:
        btnLamMoi.setBackground(new Color(100,181,246));
    }//GEN-LAST:event_btnLamMoiMouseEntered

    private void btnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseExited
        // TODO add your handling code here:
        btnLamMoi.setBackground(white);
    }//GEN-LAST:event_btnLamMoiMouseExited

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblSinhVien.getSelectedRow();
        if (evt.getClickCount() == 2 && row >= 0) {
            // Hiện nút Sửa, Xóa ẩn thêm 
            btnThem.setEnabled(false);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);

            // Chuyển sang tab Biểu mẫu
            jTabbedPane1.setSelectedIndex(1);

            // Hiển thị dữ liệu lên form
            showDetail(row);
        }
    }

    private void showDetail(int row) {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        System.out.println("==== Dữ liệu dòng " + row + " ====");
        for (int i = 0; i < model.getColumnCount(); i++) {
            System.out.println("Cột " + i + ": " + model.getValueAt(row, i));
        }
        txtMaSv.setText(getString(model.getValueAt(row, 0)));
        txtHoTen.setText(getString(model.getValueAt(row, 1)));
        txtNgSinh.setText(getString(model.getValueAt(row, 2)));
        txtDiaChi.setText(getString(model.getValueAt(row, 4)));
        txtSDT.setText(getString(model.getValueAt(row, 5)));
        txtEmail.setText(getString(model.getValueAt(row, 6)));
        txtMaLop.setText(getString(model.getValueAt(row, 7)));
    
        // Đổ dữ liệu cho ComboBox giới tính
        String gioiTinh = getString(model.getValueAt(row, 3)).trim();
        if (gioiTinh.equalsIgnoreCase("Nam")) {
            cboGioiTinh.setSelectedItem("Nam");
        } else {
            cboGioiTinh.setSelectedItem("Nữ");
        }
    
        // Đổ dữ liệu cho ComboBox trạng thái
        String trangThai = getString(model.getValueAt(row, 8)).trim();
        if (trangThai.equalsIgnoreCase("Đang học")) {
            cboTrangThai.setSelectedItem("Đang học");
        } else if (trangThai.equalsIgnoreCase("Nghỉ học")) {
            cboTrangThai.setSelectedItem("Nghĩ học");
        } else if (trangThai.equalsIgnoreCase("Tốt nghiệp")) {
            cboTrangThai.setSelectedItem("Tốt nghiệp");
        } else {
            cboTrangThai.setSelectedIndex(0);
        }
    
        txtMaSv.setEditable(false);
    }
    
    // Thêm hàm tiện ích này vào class
    private String getString(Object value) {
        return value == null ? "" : value.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SinhVienJDialog dialog = new SinhVienJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoChonTatCa;
    private javax.swing.JButton btnChonTatCa;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaDaChon;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaSv;
    private javax.swing.JTextField txtNgSinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimMaSv;
    // End of variables declaration//GEN-END:variables
    private void fillTableSinhVien() {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        // lấy danh sách sinh viên từ dtb 
        SinhVienDAO dao = new SinhVienDAOImpl();
        List<SinhVien> list = dao.selectAll();
        // tạo đối tượng dao và lấy toàn bộ sinh viên từ dtb 
        for (SinhVien sv : list) {
            // Chuyển trạng thái số sang chữ
            String trangThaiText;
            switch (sv.getTrangThai()) {
                case "0":
                    trangThaiText = "Đang học";
                    break;
                case "1":
                    trangThaiText = "Nghỉ học";
                    break;
                case "2":
                    trangThaiText = "Tốt nghiệp";
                    break;
                default:
                    trangThaiText = "Không xác định";
            }
            // Chuyển giới tính số sang chữ
            String gioiTinhText = "0".equals(sv.getGioiTinh()) ? "Nữ" : "Nam";

            model.addRow(new Object[]{
                sv.getMaSV(),
                sv.getHoTen(),
                sv.getNgaySinh(),
                gioiTinhText, // Hiển thị chữ thay vì số
                sv.getDiaChi(),
                sv.getSdt(),
                sv.getEmail(),
                sv.getMaLop(),
                trangThaiText,
                false // Cột checkbox, mặc định là false
            });
        }
    }

    private void checkAll() {
        // duyệt qua tất cả các dòng trên bảng 
        for (int i = 0; i < tblSinhVien.getRowCount(); i++) {
            tblSinhVien.setValueAt(true, i, 9); // cột 9 là cột checkbox
        }
    }

    private void boChonTatCa() {
        for (int i = 0; i < tblSinhVien.getRowCount(); i++) {
            tblSinhVien.setValueAt(false, i, 9); // cột 9 là cột checkbox
        }
    }

    private void xoaDaChon() {
    DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
    SinhVienDAO dao = new SinhVienDAOImpl();
    boolean hasBlocked = false;
    // Duyệt ngược để tránh lỗi khi xóa dòng
    for (int i = model.getRowCount() - 1; i >= 0; i--) {
        Boolean checked = (Boolean) model.getValueAt(i, 9); // cột 9 là checkbox
        String trangThai = model.getValueAt(i, 8).toString().trim(); // cột 8 là trạng thái
        if (checked != null && checked) {
            if ("Đang học".equalsIgnoreCase(trangThai)) {
                hasBlocked = true;// đánh dấu ko dc xóa 
                continue; // Không xóa sinh viên đang học
            }
            String maSV = model.getValueAt(i, 0).toString();
            dao.delete(maSV); // Xóa trên database
            model.removeRow(i); // Xóa trên bảng giao diện
        }
    }
    fillTableSinhVien(); // Load lại bảng từ database
    // thông báo nếu sinh viên bị chặn xóa 
    if (hasBlocked) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Không thể xóa sinh viên có trạng thái 'Đang học'!");
    }
}
    
    // sự kiện thêm 
    public void them() {
        // lấy dữ liệu từ form nhập 
        String maSV = txtMaSv.getText().trim();
        String hoTen = txtHoTen.getText().trim();
        String ngaySinh = txtNgSinh.getText().trim();
        String gioiTinh = cboGioiTinh.getSelectedItem() != null ? cboGioiTinh.getSelectedItem().toString() : "";
        String diaChi = txtDiaChi.getText().trim();
        String sdt = txtSDT.getText().trim();
        String email = txtEmail.getText().trim();
        String maLop = txtMaLop.getText().trim();
        String trangThai = cboTrangThai.getSelectedItem() != null ? cboTrangThai.getSelectedItem().toString() : "";
        // kiểm tra tất cả thông htoong tin ko được trống 
        if (maSV.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên!");
            return;
        }
        SinhVienDAO dao = new SinhVienDAOImpl();
        if (dao.selectByMaSV(maSV).size() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã sinh viên đã tồn tại!");
            return;
        }
        if (hoTen.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên!");
            return;
        }
        if (ngaySinh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh!");
            return;
        }
        if (gioiTinh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính!");
            return;
        }
        if (diaChi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ!");
            return;
        }
        if (sdt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!");
            return;
        }
        if (email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập email!");
            return;
        }
        if (maLop.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã lớp!");
            return;
        }
        if (trangThai.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái!");
            return;
        }
    
        // Chuyển giới tính về số
        String gioiTinhValue = gioiTinh.equals("Nam") ? "1" : "0";
        // Chuyển trạng thái về số
        String trangThaiValue;
        switch (trangThai.trim()) {
            case "Đang học": trangThaiValue = "0"; break;
            case "Nghỉ học": trangThaiValue = "1"; break;
            case "Tốt nghiệp": trangThaiValue = "2"; break;
            default: trangThaiValue = "0";
        }
      // tạo đối tượng sinh viên mới 
        SinhVien sv = new SinhVien(maSV, hoTen, ngaySinh, gioiTinhValue, diaChi, sdt, email, maLop, trangThaiValue);
        dao.insert(sv);
        fillTableSinhVien();
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công!");
    }
    public void sua() {
        String maSV = txtMaSv.getText().trim();
        String hoTen = txtHoTen.getText().trim();
        String ngaySinh = txtNgSinh.getText().trim();
        String gioiTinh = cboGioiTinh.getSelectedItem() != null ? cboGioiTinh.getSelectedItem().toString() : "";
        String diaChi = txtDiaChi.getText().trim();
        String sdt = txtSDT.getText().trim();
        String email = txtEmail.getText().trim();
        String maLop = txtMaLop.getText().trim();
        String trangThai = cboTrangThai.getSelectedItem() != null ? cboTrangThai.getSelectedItem().toString() : "";
    
        // Kiểm tra dữ liệu như nút thêm
        if (maSV.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên!");
            return;
        }
        if (hoTen.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên!");
            return;
        }
        if (ngaySinh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh!");
            return;
        }
        if (gioiTinh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính!");
            return;
        }
        if (diaChi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ!");
            return;
        }
        if (sdt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!");
            return;
        }
        if (email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập email!");
            return;
        }
        if (maLop.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã lớp!");
            return;
        }
        if (trangThai.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái!");
            return;
        }
    
        // Chuyển giới tính về số
        String gioiTinhValue = gioiTinh.equals("Nam") ? "1" : "0";
        // Chuyển trạng thái về số
        String trangThaiValue;
        switch (trangThai.trim()) {
            case "Đang học": trangThaiValue = "0"; break;
            case "Nghỉ học": trangThaiValue = "1"; break;
            case "Tốt nghiệp": trangThaiValue = "2"; break;
            default: trangThaiValue = "0";
        }
    
        SinhVien sv = new SinhVien(maSV, hoTen, ngaySinh, gioiTinhValue, diaChi, sdt, email, maLop, trangThaiValue);
        SinhVienDAO dao = new SinhVienDAOImpl();
        dao.update(sv);
        lamMoiForm(); // Làm mới form sau khi cập nhật
        fillTableSinhVien();
        javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thành công!");
}
public void xoa() {
    // lấy mã sinh viên và vị trí dòng được vchojn 
    // ếu chưa chọn dòng nào thì thông báo lỗi 
    String maSV = txtMaSv.getText().trim();
    DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
    int row = tblSinhVien.getSelectedRow();
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa!");
        return;
    }
    // nếu trạng thái là đang học thì cũng không xóa được 
    String trangThai = model.getValueAt(row, 8).toString().trim(); // cột 8 là trạng thái
    if ("Đang học".equalsIgnoreCase(trangThai)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa sinh viên có trạng thái 'Đang học'!");
        return;
    }
    // hiển thị hộp thoại có chắc chắn muốn xóa hay không 
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn xóa sinh viên này?",
        "Xác nhận xóa",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    // nếu chọn   khác yes thì return luôn  
    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }
    // xác nhận thì gọi dao để xóa sinh viên luôn 
    SinhVienDAO dao = new SinhVienDAOImpl();
    dao.delete(maSV);
    fillTableSinhVien();
    lamMoiForm(); // Làm mới form sau khi xóa
    javax.swing.JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!");
}
public void lamMoiForm() {
    // xóa trắng tất cả các ô dữ liệu 
    txtMaSv.setText("");
    txtHoTen.setText("");
    txtNgSinh.setText("");
    cboGioiTinh.setSelectedIndex(0);
    txtDiaChi.setText("");
    txtSDT.setText("");
    txtEmail.setText("");
    txtMaLop.setText("");
    cboTrangThai.setSelectedIndex(0);

    txtMaSv.setEditable(true); // Cho phép nhập lại mã SV

    btnThem.setEnabled(true);
    btnSua.setEnabled(false);
    btnXoa.setEnabled(false);
}
}
