/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package qlsv.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;

import qlsv.dao.impl.LopDAOImpl;
import qlsv.dao.impl.ThoiKhoaBieuDAOImpl;
import qlsv.enity.ThoiKhoaBieu;

/**
 *
 * @author ADMIN
 */
public class ThoiKhoaBieuJDialog extends javax.swing.JDialog {

    ThoiKhoaBieuDAOImpl tkbDAO = new ThoiKhoaBieuDAOImpl();

    /**
     * Creates new form ThoiKhoaBieuJDialog
     */
    public ThoiKhoaBieuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadLopToComboBox();
        btnLuu.setEnabled(false);
        setLocationRelativeTo(null);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/abc.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboLopTKB = new javax.swing.JComboBox<>();
        btnXemTKB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKB = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboThuTKB = new javax.swing.JComboBox<>();
        txtTietBD = new javax.swing.JTextField();
        txtSoTiet = new javax.swing.JTextField();
        txtMaGV = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        txtTenGV = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblTongMonHoc = new javax.swing.JLabel();
        lblTongGV = new javax.swing.JLabel();
        lblTongSoTiet = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý thời khóa biểu - Nguyễn Phi Thông");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THỜI KHÓA BIỂU");

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\CHINH.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Chọn lớp : ");

        cboLopTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopTKBActionPerformed(evt);
            }
        });

        btnXemTKB.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XEMTKB (2).png")); // NOI18N
        btnXemTKB.setText("Xem thời khóa biểu");
        btnXemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTKBActionPerformed(evt);
            }
        });

        tblTKB.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {},
    new String [] {
        "ID", "Thứ", "Tiết bắt đầu", "Số tiết", "Mã môn", "Tên môn", "Mã GV", "Tên GV", "Phòng", "Ghi chú", ""
    }// tao đa thêm id ở đây 
) {
    Class[] types = new Class [] {
        java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
        java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
        java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
    };
    boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false, false, false, true
    };

    public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
    }
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
});
        jScrollPane1.setViewportView(tblTKB);

        btnSua.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\UPDATE.png")); // NOI18N
        btnSua.setText("Sủa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THEM.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\LamMoi (1).png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\XOA-RED.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setText("Thông tin chi tiết ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Thứ : ");

        jLabel5.setText("Tiết bắt đầu : ");

        jLabel6.setText("Mã môn : ");

        jLabel7.setText("Số tiết : ");

        jLabel8.setText("Tên môn : ");

        jLabel9.setText("Tên giáo viên : ");

        jLabel10.setText("Phòng : ");

        jLabel11.setText("Mã giáo viên : ");

        jLabel12.setText("Ghi chú : ");

        cboThuTKB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ 2", "Thứ 3 ", "Thứ 4", "Thứ 5", "Thứ 6 ", "Thứ 7" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboThuTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTietBD, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(157, 157, 157)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboThuTKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTietBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Chức năng ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnLuu.setBackground(new java.awt.Color(255, 255, 102));
        btnLuu.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Luu.png")); // NOI18N
        btnLuu.setText("Lưu ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\Huy.png")); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Thống kê nhanh ");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Tổng số môn học : ");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Tổng số tiết : ");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Tổng số giảng viên : ");

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\ALL MÔN\\SUMMER_2025_BLOCK_2\\DUAN_1\\ANHDUAN\\THONGKE.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTongSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTongMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTongGV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnLuu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHuy)))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboLopTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXemTKB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnLamMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLopTKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemTKB))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnHuy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblTongMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblTongSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblTongGV, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboLopTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopTKBActionPerformed
        // TODO add your handling code here:
//        String maLop = (String) cboLopTKB.getSelectedItem();
//        if (maLop != null) {
//            loadTKBToTable(maLop);
//        }

    }//GEN-LAST:event_cboLopTKBActionPerformed

    private void btnXemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTKBActionPerformed
        // TODO add your handling code here:
        String maLop = (String) cboLopTKB.getSelectedItem();

        if (maLop != null) {
            loadTKBToTable(maLop);
        }
    }//GEN-LAST:event_btnXemTKBActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        duLieuLenForm();
        btnLuu.setEnabled(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn hủy không?",
                "Xác nhận hủy",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThoiKhoaBieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThoiKhoaBieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThoiKhoaBieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThoiKhoaBieuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThoiKhoaBieuJDialog dialog = new ThoiKhoaBieuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXemTKB;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLopTKB;
    private javax.swing.JComboBox<String> cboThuTKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongGV;
    private javax.swing.JLabel lblTongMonHoc;
    private javax.swing.JLabel lblTongSoTiet;
    private javax.swing.JTable tblTKB;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSoTiet;
    private javax.swing.JTextField txtTenGV;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtTietBD;
    // End of variables declaration//GEN-END:variables
    // đổ dữ liệu lên bảng 
    private void loadTKBToTable(String maLop) {
    List<ThoiKhoaBieu> list = tkbDAO.selectByLop(maLop);
    DefaultTableModel model = (DefaultTableModel) tblTKB.getModel();
    model.setRowCount(0);
    tblTKB.setDefaultRenderer(Boolean.class, tblTKB.getDefaultRenderer(Boolean.class));
    for (ThoiKhoaBieu tkb : list) {
        model.addRow(new Object[]{
            tkb.getId(), // cột id
            tkb.getThu(),
            tkb.getTietBatDau(),
            tkb.getSoTiet(),
            tkb.getMaMH(),
            tkb.getTenMH(),
            tkb.getMaGV(),
            tkb.getTenGV(),
            tkb.getPhongHoc(),
            tkb.getGhiChu(),
            Boolean.FALSE // cột checkbox kiểu Boolean
        });
    }
    // Ẩn cột id (cột đầu tiên)
    tblTKB.getColumnModel().getColumn(0).setMinWidth(0);
    tblTKB.getColumnModel().getColumn(0).setMaxWidth(0);
    tblTKB.getColumnModel().getColumn(0).setWidth(0);

    thongKeNhanh(maLop);
}

// đổ dữ lliệul lên cbo
    private void loadLopToComboBox() {
        LopDAOImpl lopDAO = new LopDAOImpl();
        List<String> dsLop = lopDAO.getAllMaLop();
        cboLopTKB.removeAllItems();
        for (String maLop : dsLop) {
            cboLopTKB.addItem(maLop);
        }
    }

    // đổ dữ liệu lên form 
   private void duLieuLenForm() {
    int row = tblTKB.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa!");
        return;
    }
    // Cột 0: id (ẩn), 1: Thứ, 2: Tiết bắt đầu, 3: Số tiết, 4: Mã môn, 5: Tên môn, 6: Mã GV, 7: Tên GV, 8: Phòng, 9: Ghi chú, 10: Checkbox
    String thuDB = tblTKB.getValueAt(row, 1).toString();
    String thuForm = "";
    switch (thuDB.trim()) {
        case "T2": thuForm = "Thứ 2"; break;
        case "T3": thuForm = "Thứ 3"; break;
        case "T4": thuForm = "Thứ 4"; break;
        case "T5": thuForm = "Thứ 5"; break;
        case "T6": thuForm = "Thứ 6"; break;
        case "T7": thuForm = "Thứ 7"; break;
        default: thuForm = "Thứ 2";
    }
    for (int i = 0; i < cboThuTKB.getItemCount(); i++) {
        if (cboThuTKB.getItemAt(i).trim().equals(thuForm)) {
            cboThuTKB.setSelectedIndex(i);
            break;
        }
    }

    txtTietBD.setText(tblTKB.getValueAt(row, 2).toString());
    txtSoTiet.setText(tblTKB.getValueAt(row, 3).toString());
    txtMaMon.setText(tblTKB.getValueAt(row, 4).toString());
    txtTenMon.setText(tblTKB.getValueAt(row, 5).toString());
    txtMaGV.setText(tblTKB.getValueAt(row, 6).toString());
    txtTenGV.setText(tblTKB.getValueAt(row, 7).toString());
    txtPhong.setText(tblTKB.getValueAt(row, 8).toString());
    txtGhiChu.setText(tblTKB.getValueAt(row, 9).toString());

    // Khóa các trường không được sửa
    txtMaMon.setEditable(false);
    txtTenMon.setEditable(false);
    txtMaGV.setEditable(false);
    txtTenGV.setEditable(false);
    txtMaMon.setEnabled(false);
    txtTenMon.setEnabled(false);
    txtMaGV.setEnabled(false);
    txtTenGV.setEnabled(false);
}

    // sưarr thông tin 
    private void sua() {
        
        int row = tblTKB.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn thông tin cần sửa!");
            return;
        }
        int id = Integer.parseInt(tblTKB.getValueAt(row, 0).toString());
        // Kiểm tra không được để trống thông tin
        if (txtTietBD.getText().trim().isEmpty()
                || txtSoTiet.getText().trim().isEmpty()
                || txtPhong.getText().trim().isEmpty()
                || txtMaMon.getText().trim().isEmpty()
                || txtTenMon.getText().trim().isEmpty()
                || txtMaGV.getText().trim().isEmpty()
                || txtTenGV.getText().trim().isEmpty()
                || txtGhiChu.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        try {
            int tietBD = Integer.parseInt(txtTietBD.getText().trim());
            int soTiet = Integer.parseInt(txtSoTiet.getText().trim());
            if (tietBD <= 0 || soTiet <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tiết bắt đầu và số tiết phải là số nguyên dương!");
                return;
            }
            // Hiển thị hộp thoại chọn học kỳ
            List<String> dsHocKy = tkbDAO.getAllMaHK();
            if (dsHocKy.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không có học kỳ nào để chọn!");
                return;
            }
            String[] arrHocKy = dsHocKy.toArray(new String[0]);
            String maHK = (String) javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Vui lòng chọn học kỳ:",
                    "Chọn học kỳ",
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    arrHocKy,
                    arrHocKy[arrHocKy.length - 1]
            );
            if (maHK == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa chọn học kỳ!");
                return;
            }
            ThoiKhoaBieu tkb = new ThoiKhoaBieu();
            tkb.setId(Integer.parseInt(tblTKB.getValueAt(row, 0).toString()));
            tkb.setThu(convertThuToDB((String) cboThuTKB.getSelectedItem()));
            tkb.setTietBatDau(tietBD);
            tkb.setSoTiet(soTiet);
            tkb.setPhongHoc(txtPhong.getText().trim());
            tkb.setGhiChu(txtGhiChu.getText().trim());
            tkb.setMaMH(txtMaMon.getText().trim());
            tkb.setTenMH(txtTenMon.getText().trim());
            tkb.setMaGV(txtMaGV.getText().trim());
            tkb.setTenGV(txtTenGV.getText().trim());
            tkb.setMaHK(maHK);
            boolean ok = tkbDAO.update(tkb);
            if (ok) {
                String maLop = (String) cboLopTKB.getSelectedItem();
                loadTKBToTable(maLop);
                javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công!");
                lamMoi();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại!");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tiết bắt đầu và số tiết phải là số!");
        }
        btnLuu.setEnabled(false);
    }
// Hàm chuyển "Thứ 2" về "T2"

    private String convertThuToDB(String thuForm) {
        switch (thuForm.trim()) {
            case "Thứ 2":
                return "T2";
            case "Thứ 3":
                return "T3";
            case "Thứ 4":
                return "T4";
            case "Thứ 5":
                return "T5";
            case "Thứ 6":
                return "T6";
            case "Thứ 7":
                return "T7";
            default:
                return "T2";
        }
    }

    // hàm làm mới 
    private void lamMoi() {
        cboThuTKB.setSelectedIndex(0);
        txtTietBD.setText("");
        txtSoTiet.setText("");
        txtMaMon.setText("");
        txtTenMon.setText("");
        txtMaGV.setText("");
        txtTenGV.setText("");
        txtPhong.setText("");
        txtGhiChu.setText("");
        cboLopTKB.setSelectedIndex(0);
        tblTKB.clearSelection();
        // bật lại cho chỉnh sửa 
        txtMaMon.setEditable(true);
        txtTenMon.setEditable(true);
        txtTenGV.setEditable(true);
        txtMaGV.setEditable(true);
        txtMaMon.setEnabled(true);
        txtTenMon.setEnabled(true);
        txtMaGV.setEnabled(true);
        txtTenGV.setEnabled(true);
        // vô hhiệuhoas sau khi làm mới 
        btnLuu.setEnabled(false);
    }

    // hàm thêm 
    private void them() {
        // Kiểm tra dữ liệu nhập
        if (txtTietBD.getText().trim().isEmpty()
                || txtSoTiet.getText().trim().isEmpty()
                || txtPhong.getText().trim().isEmpty()
                || txtMaMon.getText().trim().isEmpty()
                || txtMaGV.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        String maMon = txtMaMon.getText().trim();
        String maGV = txtMaGV.getText().trim();

        // Kiểm tra mã môn đã tồn tại chưa
        if (!tkbDAO.isMaMonExist(maMon)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã môn không tồn tại!");
            return;
        }
        // Kiểm tra mã giáo viên đã tồn tại chưa
        if (!tkbDAO.isMaGVExist(maGV)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã giáo viên không tồn tại!");
            return;
        }

        try {
            int tietBD = Integer.parseInt(txtTietBD.getText().trim());
            int soTiet = Integer.parseInt(txtSoTiet.getText().trim());
            if (tietBD <= 0 || soTiet <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tiết bắt đầu và số tiết phải là số nguyên dương!");
                return;
            }
            // Hiển thị hộp thoại chọn học kỳ
            List<String> dsHocKy = tkbDAO.getAllMaHK(); // Lấy danh sách học kỳ từ DAO
            if (dsHocKy.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không có học kỳ nào để chọn!");
                return;
            }
            String[] arrHocKy = dsHocKy.toArray(new String[0]);
            String maHK = (String) javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Vui lòng chọn học kỳ:",
                    "Chọn học kỳ",
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    arrHocKy,
                    arrHocKy[arrHocKy.length - 1] // Mặc định chọn học kỳ cuối cùng (SU24)
            );
            if (maHK == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa chọn học kỳ!");
                return;
            }
            // Tạo đối tượng ThoiKhoaBieu mới
            ThoiKhoaBieu tkb = new ThoiKhoaBieu();
            tkb.setThu(convertThuToDB((String) cboThuTKB.getSelectedItem()));
            tkb.setTietBatDau(tietBD);
            tkb.setSoTiet(soTiet);
            tkb.setPhongHoc(txtPhong.getText().trim());
            tkb.setGhiChu(txtGhiChu.getText().trim());
            tkb.setMaMH(maMon);
            tkb.setMaGV(maGV);
            tkb.setMaLop((String) cboLopTKB.getSelectedItem());
            tkb.setMaHK(maHK); // Truyền học kỳ người dùng chọn
            boolean ok = tkbDAO.insert(tkb);
            if (ok) {
                String maLop = (String) cboLopTKB.getSelectedItem();
                loadTKBToTable(maLop);
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                lamMoi();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tiết bắt đầu và số tiết phải là số!");
        }
    }

    // hàm xóa 
    private void xoa() {
        int row = tblTKB.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn thông tin cần xóa!");
            return;
        }
       
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn xóa thông tin này không?\nHành động này không thể khôi phục!",
                "Xác nhận xóa",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tblTKB.getValueAt(row, 0).toString());
            boolean ok = tkbDAO.delete(id);
            if (ok) {
                String maLop = (String) cboLopTKB.getSelectedItem();
                loadTKBToTable(maLop);
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
                lamMoi();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }
// thống kê nhanh 

    private void thongKeNhanh(String maLop) {
        List<ThoiKhoaBieu> list = tkbDAO.selectByLop(maLop);
        // Tổng số môn học đếm theo mã môn không trùng lặp
        java.util.Set<String> setMonHoc = new java.util.HashSet<>();
        // Tổng số giảng viên đếm theo mã GVkhông trùng
        java.util.Set<String> setGV = new java.util.HashSet<>();
        int tongSoTiet = 0;
        for (ThoiKhoaBieu tkb : list) {
            setMonHoc.add(tkb.getMaMH());
            setGV.add(tkb.getMaGV());
            tongSoTiet += tkb.getSoTiet();
        }
        lblTongMonHoc.setText(String.valueOf(setMonHoc.size()));
        lblTongGV.setText(String.valueOf(setGV.size()));
        lblTongSoTiet.setText(String.valueOf(tongSoTiet));
    }

}
